{
 "title": "Bucket Overview Extended",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "bucket" }
  ]
 },
 "panels": [
  {
   "title": "$bucket: sum(irate(kv_ops[1m]))",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kv_ops{bucket=\"$bucket\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$bucket: 90th percentile GET latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, irate(kv_cmd_duration_seconds_bucket{opcode=\"GET\",bucket=\"$bucket\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$bucket: irate(kv_ep_bg_fetched[1m]))",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " irate(kv_ep_bg_fetched[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "$bucket: kv_ep_diskqueue_items",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_diskqueue_items{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$bucket: kv_vb_ops_create",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kv_vb_ops_create{bucket=\"$bucket\",state=\"active\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$bucket: Percentage Memory Resident",
   "type": "timeseries",
   "description": "kv_vb_perc_mem_resident_ratio",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_vb_perc_mem_resident_ratio{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "irate(kv_ops[1m])",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(kv_ops[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "kv_memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_mem_used_bytes{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kv_ep_db_data_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kv_ep_db_data_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "kv items",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_vb_curr_items{state=~\"active|replica\",bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV Mutations",
   "type": "timeseries",
   "description": "Computed as:`(irate(kv_ops{op=~\"set|set_meta|set_ret_meta|cas|decr|del_meta|del_ret_meta|incr|delete\"}[5m]))`",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(irate(kv_ops{op=~\"set|set_meta|set_ret_meta|cas|decr|del_meta|del_ret_meta|incr|delete\",bucket=\"$bucket\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kv_disk",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_ep_diskqueue_items{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kv resident items",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_curr_items_tot{bucket=\"$bucket\"} - ignoring(name) kv_ep_num_non_resident{bucket=\"$bucket\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}