{
 "title": "Check History",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Check History",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "multimanager_cluster_checker_status{cluster_name=~`${cluster:regex}`}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node Check History",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "multimanager_node_checker_status{cluster_name=~`${cluster:regex}`}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bucket Check History",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "multimanager_bucket_checker_status{cluster_name=~`${cluster:regex}`}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}