{
 "title": "Single Cluster Overview",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "multimanager_cluster_checker_status{cluster_name=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview - at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$cluster", "language": "jsonata", "name": "Cluster Name", "type": "number" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")})",
       "language": "jsonata",
       "name": "Version",
       "type": "number"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$count($.nodes_summary[*])", "language": "jsonata", "name": "Number of nodes" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$count($.buckets_summary[*])", "language": "jsonata", "name": "Number of buckets" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Health Check Warnings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} > 0)",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} > 0)",
     "legendFormat": "Node"
    },
    {
     "expr": "count(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} > 0)",
     "legendFormat": "Bucket"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*].host, function($h) {\n    $replace(\n      $replace($h, /:\\d+$/, \"\")\n    , /https?:\\/\\//, \"\")\n})",
       "language": "jsonata",
       "name": "Node"
      },
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")})",
       "language": "jsonata",
       "name": "Version"
      },
      { "jsonPath": "$.nodes_summary[*].os", "language": "jsonpath", "name": "Operating System" },
      {
       "jsonPath": "$map($.nodes_summary[*], function($node) {\n  $join($sort($map($node.services, function ($svc) {\n    $svc = \"cbas\" ? \"Analytics\" :\n    $svc = \"n1ql\" ? \"Query\" :\n    $svc = \"eventing\" ? \"Eventing\" :\n    $svc = \"index\" ? \"Index\" :\n    $svc = \"fts\" ? \"Search\" :\n    $svc = \"kv\" ? \"Data\" :\n    $svc = \"backup\" ? \"Backup\" : $svc\n  })), \", \")\n})",
       "language": "jsonata",
       "name": "Services"
      },
      { "jsonPath": "$.nodes_summary[*].cpuCount", "language": "jsonata", "name": "CPUs" },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  $formatNumber($round($node.mem_total / 1024 / 1024 / 1024), \"####;(#0.00)\")\n})",
       "language": "jsonata",
       "name": "Total RAM"
      },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  $round((1 - ($node.mem_free / $node.mem_total)) * 100, 2)\n})",
       "language": "jsonata",
       "name": "RAM Usage"
      },
      { "jsonPath": "$.nodes_summary[*].node_uuid", "language": "jsonpath", "name": "uuid" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Running Services (clickable!)",
   "type": "stat",
   "description": "Click on each service to be taken to its dashboard page.",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"kv\"}) ~> $count",
       "language": "jsonata",
       "name": "Data"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"index\"}) ~> $count",
       "language": "jsonata",
       "name": "Index"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"fts\"}) ~> $count",
       "language": "jsonata",
       "name": "Search"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"n1ql\"}) ~> $count",
       "language": "jsonata",
       "name": "Query"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"eventing\"}) ~> $count",
       "language": "jsonata",
       "name": "Eventing"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"cbas\"}) ~> $count",
       "language": "jsonata",
       "name": "Analytics"
      },
      {
       "jsonPath": "$.nodes_summary.services ~> $filter(function($svc) {$svc = \"backup\"}) ~> $count",
       "language": "jsonata",
       "name": "Backup"
      },
      { "jsonPath": "0", "language": "jsonata", "name": "..." }
     ],
     "method": "GET",
     "urlPath": "/clusters"
    }
   ]
  },
  {
   "title": "Dataset",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.buckets_summary[*].name", "name": "bucket" },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $formatNumber($b.items, \"#,###\")\n})",
       "language": "jsonata",
       "name": "Items Stored"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $b.quota / 1024 / 1024 / 1024\n})",
       "language": "jsonata",
       "name": "Quota"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $round($b.quota_used, 2)\n})",
       "language": "jsonata",
       "name": "Quota Used",
       "type": "number"
      },
      {
       "jsonPath": "$.buckets_summary[*].num_replicas",
       "language": "jsonata",
       "name": "Replicas"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "count by (bucket) (index_items_count{cluster=`$cluster`}) or max by (bucket) (clamp_max(kv_ops, 0))",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "expr": "min by (bucket) (kv_vb_perc_mem_resident_ratio{cluster=`$cluster`,state=\"active\"})"
    }
   ]
  },
  {
   "title": "Basic Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "Cluster Check Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    }
   ]
  },
  {
   "title": "Node Check Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 19 },
   "targets": [
    {
     "expr": "multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    }
   ]
  },
  {
   "title": "Bucket Check Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "expr": "multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    }
   ]
  },
  { "title": "KPIs - Data Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "GET Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ops{cluster=\"$cluster\",op=\"get\"}[$__rate_interval]))",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\"}[5m]))))",
     "legendFormat": "99%"
    },
    {
     "expr": "max(histogram_quantile(0.999, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\"}[5m]))))",
     "legendFormat": "99.9%"
    },
    {
     "expr": "max(histogram_quantile(0.50, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\"}[5m]))))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "SET Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ops{cluster=\"$cluster\",op=\"set\"}[$__rate_interval]))",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\"}[5m]))))",
     "legendFormat": "99%"
    },
    {
     "expr": "max(histogram_quantile(0.999, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\"}[5m]))))",
     "legendFormat": "99.9%"
    },
    {
     "expr": "max(histogram_quantile(0.50, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\"}[5m]))))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "KPIs - Query Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(n1ql_requests{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(n1ql_request_time[$__rate_interval]) / increase(n1ql_requests[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}