{
 "title": "Couchbase Kubernetes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   },
   { "name": "bucket", "label": "bucket", "query": { "query": "label_values(bucket)" } },
   { "name": "node", "label": "node", "query": { "query": "label_values(couchbase_node)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cpu_utilization_rate{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_mem_used_bytes{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    },
    {
     "expr": "cbbucketstat_mem_actual_used_bytes{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    },
    {
     "expr": "cbbucketstat_mem_actual_used_free{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cbpernodebucket_curr_connections{kubernetes_pod_name=~\"$pod\", couchbase_node=~\"$node\", bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Ops Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_ops{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Gets Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cmd_get{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Sets Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cmd_set{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Items",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cbpernodebucket_curr_items{kubernetes_pod_name=~\"$pod\", couchbase_node=~\"$node\", bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Disk Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_disk_write_queue{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    },
    {
     "expr": "cbbucketstat_ep_diskqueue_items{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_couch_total_disk_size{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "vBucket Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_vbuckets_active_queue_size{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\", couchbase_node=~\"$node\"}"
    },
    {
     "expr": "cbpernodebucket_vb_pending_queue_size{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\", couchbase_node=~\"$node\"}"
    },
    {
     "expr": "cbpernodebucket_vb_replica_queue_size{kubernetes_pod_name=~\"$pod\", bucket=~\"$bucket\", kubernetes_namespace=~\"$namespace\", couchbase_node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Items Total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cbpernodebucket_curr_items_tot{kubernetes_pod_name=~\"$pod\", couchbase_node=~\"$node\", bucket=~\"$bucket\"}"
    }
   ]
  }
 ]
}