{
 "title": "Demo checks",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Event log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/opt/couchbase/var/lib/couchbase/logs/db1/events_db1.log\",job=\"couchbase-microlith\"}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Bucket checks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "multimanager_bucket_checker_status{status=\"warn\"}",
     "legendFormat": "WARNING-{{bucket}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cluster checks",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "multimanager_cluster_checker_status{status=\"warn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}