{
 "title": "Healthcheck",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  {
   "title": "Enable advanced monitoring",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"/public/img/cblogo.png\" width=\"250\" />\n\n\n# Advanced monitoring\n[\"Get access to shiny new features!\"](http://www.couchbase.com/advanced-monitoring-signup)"
   }
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 } },
  {
   "title": "Specific metric problems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode!=\"idle\"}[10s])",
     "legendFormat": "CPU {{cpu}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Specific log problems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({job=\"couchbase-fluentbit\"}|=\"Slow\"[30s])",
     "legendFormat": "Slow operations"
    },
    {
     "expr": "rate({job=\"couchbase-fluentbit\",level=\"ERROR\"}[30s])",
     "legendFormat": "Error - {{filename}}"
    }
   ]
  },
  { "title": "System checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"nodeexporter:9100\", job=\"nodeexporter\"} - node_boot_time_seconds{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Port checks",
   "type": "stat",
   "description": "Various bespoke port checks run by custom metric collector",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cbip_db1_port_8091_open\n", "legendFormat": "DB1 - 8091" },
    { "expr": "cbip_db1_port_12345_open", "legendFormat": "DB1 - 12345" },
    { "expr": "cbip_db2_port_8091_open", "legendFormat": "DB2 - 8092" }
   ]
  },
  {
   "title": "Disk usage of docs per node",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (cbnode_interestingstats_couch_docs_actual_disk_size)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Couchbase Node CPU utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbnode_systemstats_cpu_utilization_rate"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Couchbase log levels per minute",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"couchbase-fluentbit\"}[1m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Couchbase Server logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"couchbase-fluentbit\"}|json|__error__=\"\"|label_format filename=`{{ Replace .filename \"/opt/couchbase/var/lib/couchbase/logs/\" \"\" -1  }}`"
    }
   ]
  },
  {
   "title": "Couchbase logs rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, filename)(rate({job=\"couchbase-fluentbit\"}[$__interval]))",
     "legendFormat": "{{filename}}"
    }
   ]
  }
 ]
}