{
 "title": "Index Service Overview",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "couchbase-service-gsi"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "query_result(multimanager_node_checker_status{cluster_name=${cluster:doublequote}})"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "query_result(max by (cluster_uuid) (multimanager_cluster_checker_status{cluster_name=${cluster:doublequote}}))"
    }
   },
   {
    "name": "node_uuid",
    "query": {
     "query": "query_result(max by (node_uuid) (multimanager_node_checker_status{node_name=~`${node:regex}(:[0-9]*)?`}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Indexes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (bucket, scope, collection, index) (index_resident_percent))"
    }
   ]
  },
  {
   "title": "Total Index Size on Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (index_data_size_on_disk{instance=~`$node(?::[0-9]*)?$`})"
    }
   ]
  },
  {
   "title": "Total Index Size in Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (index_memory_used{instance=~`$node(?::[0-9]*)?$`})"
    }
   ]
  },
  {
   "title": "Items Indexed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(index_items_count{instance=~`$node(?::[0-9]*)?$`})"
    }
   ]
  },
  {
   "title": "Largest Indexes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, index_data_size{instance=~`$node(?::[0-9]*)?$`})",
     "legendFormat": "{{bucket}}/{{index}}"
    }
   ]
  },
  {
   "title": "Slowest Scanning Indexes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (bucket, index) (index_avg_scan_latency{instance=~`$node(?::[0-9]+)?$`}))",
     "legendFormat": "{{bucket}} / {{ index }}"
    }
   ]
  },
  {
   "title": "Index Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, sum by (bucket, index) (rate(index_num_requests{instance=~`$node(?::[0-9]*)?$`}[$__rate_interval])))",
     "legendFormat": "{{bucket}} / {{index}}"
    }
   ]
  },
  {
   "title": "Indexes Never Scanned",
   "type": "table",
   "description": "Indexes that have never been scanned and may be redundant.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(sum by (bucket, scope, collection, index) (index_num_requests{instance=~`$node(?::[0-9]*)?$`})) == 0"
    }
   ]
  },
  {
   "title": "Pending Documents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "sum(index_num_docs_pending{instance=~`^$node(?::[0-9]*)?$`})",
     "legendFormat": "Documents"
    }
   ]
  }
 ]
}