{
 "title": "Node Overview (7.x)",
 "tags": [
  "couchbase",
  "couchbase-node",
  "couchbase-7"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "query_result(max by (cluster_uuid) (multimanager_cluster_checker_status{cluster_name=${cluster:doublequote}}))"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "query_result(multimanager_node_checker_status{cluster_name=${cluster:doublequote}})"
    }
   },
   {
    "name": "node_uuid",
    "query": {
     "query": "query_result(max by (node_uuid) (multimanager_node_checker_status{node_name=~`${node:regex}(:[0-9]*)?`}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Check Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "multimanager_node_checker_status{cluster_name=${cluster:doublequote},node_name=~`${node:regex}(:[0-9]*)?`} > 0"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_utilization_rate{instance=~`${node:regex}(:[0-9]*)?$`}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_mem_free{cluster=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?`} / \nsys_mem_total{cluster=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?`}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage by Process",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sysproc_mem_resident{cluster=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?$`}",
     "legendFormat": "{{ proc }}"
    }
   ]
  },
  {
   "title": "CPU Usage by Process",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sysproc_cpu_utilization{cluster=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?$`}",
     "legendFormat": "{{ proc }}"
    }
   ]
  }
 ]
}