{
 "title": "Node Overview",
 "tags": [
  "couchbase",
  "couchbase-node",
  "couchbase-7"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "DS_ALERTMANAGER_API", "query": "marcusolsson-json-datasource" },
   {
    "name": "DS_COUCHBASE_CLUSTER_MONITOR_API",
    "query": "marcusolsson-json-datasource"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "query_result(max by (cluster_uuid) (multimanager_cluster_checker_status{cluster_name=${cluster:doublequote}}))"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "query_result(multimanager_node_checker_status{cluster_name=${cluster:doublequote}})"
    }
   },
   {
    "name": "node_uuid",
    "query": {
     "query": "query_result(max by (node_uuid) (multimanager_node_checker_status{node_name=~`${node:regex}(:[0-9]*)?`}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.version ~> function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")}",
       "language": "jsonata",
       "name": "Version"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid/node/$node_uuid"
    }
   ]
  },
  {
   "title": "Running Services (clickable!)",
   "type": "stat",
   "description": "Click on each service to be taken to its dashboard page.",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$.services ~> $filter(function($svc) {$svc = \"kv\"}) ~> $count",
       "language": "jsonata",
       "name": "Data"
      },
      {
       "jsonPath": "$.services ~> $filter(function($svc) {$svc = \"index\"}) ~> $count",
       "language": "jsonata",
       "name": "Index"
      },
      {
       "jsonPath": "$.services ~> $filter(function($svc) {$svc = \"fts\"}) ~> $count",
       "language": "jsonata",
       "name": "Search"
      },
      {
       "jsonPath": "$.services ~> $filter(function($svc) {$svc = \"n1ql\"}) ~> $count",
       "language": "jsonata",
       "name": "Query"
      },
      {
       "jsonPath": "$.services ~> $filter(function($svc) {$svc = \"eventing\"}) ~> $count",
       "language": "jsonata",
       "name": "Eventing"
      },
      {
       "jsonPath": "$.services ~> $filter(function($svc) {$svc = \"cbas\"}) ~> $count",
       "language": "jsonata",
       "name": "Analytics"
      },
      {
       "jsonPath": "$.services ~> $filter(function($svc) {$svc = \"backup\"}) ~> $count",
       "language": "jsonata",
       "name": "Backup"
      },
      { "jsonPath": "0", "language": "jsonata", "name": "..." }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid/node/$node_uuid"
    }
   ]
  },
  {
   "title": "Health Check Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "multimanager_node_checker_status{cluster_name=${cluster:doublequote},node_name=~`${node:regex}(:[0-9]*)?`} >= 0"
    },
    {
     "cacheDurationSeconds": 5,
     "fields": [
      { "jsonPath": "$[*].labels.health_check_id", "name": "id" },
      { "jsonPath": "$[*].labels.health_check_name", "language": "jsonpath", "name": "name" },
      {
       "jsonPath": "[$.labels.severity ~> $map(function($a) {\n$a = \"critical\" ? 30 :\n$a = \"warning\" ? 20 :\n$a = \"info\" ? 10 : -1\n})]",
       "language": "jsonata",
       "name": "Value"
      }
     ],
     "method": "GET",
     "urlPath": "/alerts?filter=job=~\"couchbase_(prometheus|fluent_bit)$\"&filter=kind=node&filter=cluster_name=${cluster:querystring}&filter=node=~\"${node:regex}(?::[0-9]*)$\""
    }
   ]
  },
  { "title": "Basic info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu_utilization_rate{instance=~`${node:regex}(:[0-9]*)?$`}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage by Process",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sysproc_cpu_utilization{cluster_name=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?$`}",
     "legendFormat": "{{ proc }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sys_mem_actual_used{cluster_name=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?`} / \nsys_mem_total{cluster_name=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?`}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage by Process",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sysproc_mem_resident{cluster_name=${cluster:doublequote},instance=~`${node:regex}(:[0-9]*)?$`}",
     "legendFormat": "{{ proc }}"
    }
   ]
  }
 ]
}