{
 "title": "Node Overview Extended",
 "time": { "from": "2024-09-20T13:42:59.393Z", "to": "2024-09-20T17:22:54.881Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(cm_outgoing_http_requests_seconds_bucket,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "sys_cpu_utilization_rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sys_cpu_utilization_rate{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "sysproc_cpu_utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_cpu_utilization{instance=\"$instance\"}",
     "legendFormat": "{{proc}}"
    }
   ]
  },
  {
   "title": "sysproc_mem_resident",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_mem_resident{instance=\"$instance\"}",
     "legendFormat": "{{proc}}"
    }
   ]
  },
  {
   "title": "kv_curr_items",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kv_curr_items{instance=\"$instance\"}",
     "legendFormat": "kv_curr_items {{bucket}}"
    }
   ]
  },
  {
   "title": "sum(irate(kv_ops[1m]))",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kv_ops{instance=\"$instance\"}[1m]))",
     "legendFormat": "sum(irate(kv_ops[1m]))"
    }
   ]
  },
  {
   "title": "kv gets and mutations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kv_ops{op=\"get\",instance=\"$instance\"}[1m]))",
     "legendFormat": "sum(irate(kv_ops{op=get}[1m]))"
    },
    {
     "expr": "sum(irate(kv_ops{op=~\"set|set_meta|set_ret_meta|cas|decr|del_meta|del_ret_meta|incr|delete\"}[1m]))",
     "legendFormat": "sum(irate(kv_ops{op=~set|set_meta|cas|delete|...}[1m]))"
    }
   ]
  },
  {
   "title": "total ops by bucket",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (bucket) (irate(kv_ops{instance=\"$instance\"}[1m]))",
     "legendFormat": "{{bucket}}: sum(irate(kv_ops[1m]))"
    }
   ]
  },
  {
   "title": "90th percentile GET latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, irate(kv_cmd_duration_seconds_bucket{instance=\"$instance\",opcode=\"GET\"}[5m]))",
     "legendFormat": "{{bucket}}-latency"
    }
   ]
  },
  {
   "title": "rate ns-server rest requests served",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cm_rest_request_leaves_total{instance=\"$instance\"}[1m])",
     "legendFormat": "$node sum(cm_rest_request_leaves_total[1m])"
    }
   ]
  },
  {
   "title": "ns-server streaming requests currently being served",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cm_rest_request_enters_total{instance=\"$instance\"} - ignoring(name) cm_rest_request_leaves_total{instance=\"$instance\"}",
     "legendFormat": "$node cm_rest_request_enters_total - cm_rest_request_leaves_total"
    }
   ]
  },
  {
   "title": "90th percentile ns-server outgoing request latencies",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, irate(cm_outgoing_http_requests_seconds_bucket{instance=\"$instance\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}