{
 "title": "NS Server Dashboard",
 "time": { "from": "2024-09-20T13:42:59.393Z", "to": "2024-09-20T17:22:54.881Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "sys_cpu_utilization_rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_cpu_utilization_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total cpu & ns-server cpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sys_cpu_utilization_rate * ignoring(name)sys_cpu_cores_available",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ns-server mem used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_mem_resident{proc=\"ns_server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate ns-server rest requests served",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cm_rest_request_leaves_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ns-server streaming requests currently being served",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cm_rest_request_enters_total - ignoring(name) cm_rest_request_leaves_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ns-server http request rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cm_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ns-server hibernated requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cm_request_hibernates_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu stolen rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_cpu_stolen_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu irq rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_cpu_irq_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sys_mem_limit and used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_mem_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ns-server mem size and resident",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_mem_size{proc=\"ns_server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sys_cpu_cores_available",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_cpu_cores_available", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ns-server major faults",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysproc_major_faults_raw{proc=\"ns_server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate ns-server major faults",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sysproc_major_faults_raw{proc=\"ns_server\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate ns-server minor faults",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(sysproc_minor_faults_raw{proc=\"ns_server\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system allocstalls",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_allocstall", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "rate of system allocstalls",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(sys_allocstall[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "system swap total and used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sys_swap_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "config merger max queue_len over 1m",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cm_ns_config_merger_queue_len_1m_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "check_time message delay",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, irate(cm_timer_lag_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}