{
 "title": "Search dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "fts_scrape_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbfts_scrape_duration_seconds" }
   ]
  },
  {
   "title": "fts_curr_batches_blocked_by_herder",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbfts_curr_batches_blocked_by_herder"
    }
   ]
  },
  {
   "title": "fts_num_bytes_used_ram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cbfts_num_bytes_used_ram" }
   ]
  },
  {
   "title": "fts_total_queries_rejected_by_herder",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbfts_total_queries_rejected_by_herder"
    }
   ]
  }
 ]
}