{
 "title": "Data Service Overview",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "couchbase-service-kv"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "query_result(multimanager_node_checker_status{cluster_name=${cluster:doublequote}})"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "query_result(max by (cluster_uuid) (multimanager_cluster_checker_status{cluster_name=${cluster:doublequote}}))"
    }
   },
   {
    "name": "node_uuid",
    "query": {
     "query": "query_result(max by (node_uuid) (multimanager_node_checker_status{node_name=~`${node:regex}(:[0-9]*)?`}))"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(multimanager_bucket_checker_status,bucket)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read Failures",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kv_ep_data_read_failed{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,bucket=~`${bucket:regex}`}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Write Failures",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kv_ep_data_write_failed{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,bucket=~`${bucket:regex}`}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Slow Runtimes / Operations",
   "type": "logs",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"couchbase-fluentbit\",hostname=~`${node:regex}(?::[0-9]*)?$`,file=\"memcached.log\"} |= \"Slow\" | json | line_format \"{{ .message }}\""
    }
   ]
  },
  {
   "title": "Bucket Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(kv_ops{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,bucket=~`${bucket:regex}`}[$__rate_interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Data Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kv_collection_mem_used_bytes{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,bucket=~`${bucket:regex}`}) by (bucket)",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "# Documents (incl. replicas)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kv_curr_items_tot{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,bucket=~`${bucket:regex}`}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Dataset Size on Disk",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couch_docs_actual_disk_size{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,bucket=~`${bucket:regex}`}",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kv_curr_connections{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`}",
     "legendFormat": "Current"
    },
    {
     "expr": "kv_daemon_connections{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "kv_system_connections{cluster=`$cluster`,instance=~`$node(?::[0-9]*)$`,bucket=~`${bucket:regex}`}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "DCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Items Remaining",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kv_dcp_items_remaining{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,connection_type!=\"\"}) by (connection_type)",
       "legendFormat": "{{ connection_type }}"
      }
     ]
    },
    {
     "title": "Items Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(kv_dcp_items_sent{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,connection_type!=\"\"}[1m])",
       "legendFormat": "{{ connection_type }}"
      }
     ]
    },
    {
     "title": "Backoff Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "targets": [
      {
       "expr": "kv_dcp_backoff{cluster=`$cluster`,instance=~`${node:regex}(?::[0-9]*)?$`,bucket=~`${bucket:regex}`}",
       "legendFormat": "{{bucket}} ({{connection_type}})"
      }
     ]
    },
    {
     "title": "Connected KV Clients",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "fields": [
        { "jsonPath": "$.connections[*].sdk_name", "name": "SDK/Client" },
        { "jsonPath": "$.connections[*].sdk_version", "language": "jsonpath", "name": "SDK Version" },
        {
         "jsonPath": "$.connections.user.($ = null ? \"\" : $replace($.name, /<\\/?ud>/, \"\"))",
         "language": "jsonata",
         "name": "Username"
        },
        { "jsonPath": "$.connections[*].source.ip", "language": "jsonpath", "name": "Source IP" },
        { "jsonPath": "$.connections[*].agent_name", "language": "jsonpath", "name": "" }
       ],
       "method": "GET",
       "urlPath": "/clusters/$cluster_uuid/connections"
      }
     ]
    }
   ]
  }
 ]
}