{
 "title": "Query Service Overview",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "couchbase-query"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "query_result(multimanager_node_checker_status{cluster_name=${cluster:doublequote}})"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "query_result(max by (cluster_uuid) (multimanager_cluster_checker_status{cluster_name=${cluster:doublequote}}))"
    }
   },
   {
    "name": "node_uuid",
    "query": {
     "query": "query_result(max by (node_uuid) (multimanager_node_checker_status{node_name=~`${node:regex}(:[0-9]*)?`}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(n1ql_requests{cluster=`$cluster`,instance=~`$node(?::[0-9]*)$`}[$__rate_interval])",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(n1ql_errors{cluster=`$cluster`,instance=~`$node(?::[0-9]*)$`}[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Query Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "irate(n1ql_warnings{cluster=`$cluster`,instance=~`$node(?::[0-9]*)$`}[$__rate_interval])",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(n1ql_request_time[$__rate_interval])) / sum(rate(n1ql_requests[$__rate_interval]))"
    }
   ]
  }
 ]
}