{
 "title": "Data Service",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "couchbase-service-kv"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "query_result(max by (cluster_uuid) (multimanager_cluster_checker_status{cluster_name=${cluster:doublequote}}))"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(multimanager_bucket_checker_status,bucket)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (kv_ep_data_read_failed{cluster=`$cluster`,bucket=~`${bucket:regex}`})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Write Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (kv_ep_data_write_failed{cluster=`$cluster`,bucket=~`${bucket:regex}`})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Bucket Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (irate(kv_ops{cluster=`$cluster`,bucket=~`${bucket:regex}`}[$__rate_interval])) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 }, "options": { "content": "# Number of documents #" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 }, "options": { "content": "# Dataset size on disk #" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 }, "options": { "content": "# Dataset size in memory #" } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 20 },
   "repeat": "bucket",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (bucket) (kv_curr_items{cluster=`$cluster`,bucket=~`${bucket:regex}`})",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 20 },
   "repeat": "bucket",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by (bucket) (couch_docs_actual_disk_size{cluster=`$cluster`,bucket=~`${bucket:regex}`}))",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 20 },
   "repeat": "bucket",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by (bucket) (kv_collection_mem_used_bytes{cluster=`$cluster`,bucket=~`${bucket:regex}`}))",
     "legendFormat": "{{ bucket }}"
    }
   ]
  },
  {
   "title": "Reads - 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n0.50,\nsum by(le,bucket) (\nrate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\",bucket=~`${bucket:regex}`}[$__rate_interval])\n)\n)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Reads - 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\",bucket=~`${bucket:regex}`}[$__rate_interval])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Reads - 99.9th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\",bucket=~`${bucket:regex}`}[$__rate_interval])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Writes - 50th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\",bucket=~`${bucket:regex}`}[$__rate_interval])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Writes - 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\",bucket=~`${bucket:regex}`}[$__rate_interval])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Writes - 99.9th percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\",bucket=~`${bucket:regex}`}[$__rate_interval])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kv_curr_connections{cluster=`$cluster`})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(kv_daemon_connections{cluster=`$cluster`})",
     "legendFormat": "Daemon"
    },
    {
     "expr": "sum(kv_system_connections{cluster=`$cluster`})",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Number of collections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (count by (instance) (kv_collection_item_count{cluster=`$cluster`,collection!=\"_default\"}))"
    }
   ]
  },
  { "title": "DCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Items Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kv_dcp_items_remaining{cluster=`$cluster`,connection_type!=\"\"}) by (connection_type)",
     "legendFormat": "{{ connection_type }}"
    }
   ]
  },
  {
   "title": "Items Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (connection_type) (irate(kv_dcp_items_sent{cluster=`$cluster`,connection_type!=\"\"}[1m]))",
     "legendFormat": "{{ connection_type }}"
    }
   ]
  },
  {
   "title": "Backoff Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "targets": [
    {
     "expr": "sum by (bucket, connection_type) (kv_dcp_backoff{cluster=`$cluster`,bucket=~`${bucket:regex}`})",
     "legendFormat": "{{bucket}} ({{connection_type}})"
    }
   ]
  },
  {
   "title": "Connected KV Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.connections[*].sdk_name", "name": "SDK/Client" },
      { "jsonPath": "$.connections[*].sdk_version", "language": "jsonpath", "name": "SDK Version" },
      {
       "jsonPath": "$.connections.user.($ = null ? \"\" : $replace($.name, /<\\/?ud>/, \"\"))",
       "language": "jsonata",
       "name": "Username"
      },
      { "jsonPath": "$.connections[*].source.ip", "language": "jsonpath", "name": "Source IP" },
      { "jsonPath": "$.connections[*].agent_name", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid/connections"
    }
   ]
  }
 ]
}