{
 "title": "Query Service",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "couchbase-query"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Query Warnings",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(n1ql_warnings{cluster_name=`$cluster`}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "irate(n1ql_errors{cluster_name=`$cluster`}[$__rate_interval])",
     "legendFormat": "{{instance}} (last $__interval)"
    }
   ]
  },
  {
   "title": "Total requests that took longer than:",
   "type": "stat",
   "description": "This is in the past time range, i.e., the value set in the top-right corner of \"Last X time unit\" (defaults to 30 minutes).",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(n1ql_requests_250ms{cluster_name=`$cluster`}[$__range])))",
     "legendFormat": "250ms"
    },
    {
     "expr": "round(sum(increase(n1ql_requests_500ms{cluster_name=`$cluster`}[$__range])))",
     "legendFormat": "500ms"
    },
    {
     "expr": "round(sum(increase(n1ql_requests_1000ms{cluster_name=`$cluster`}[$__range])))",
     "legendFormat": "1000ms"
    },
    {
     "expr": "round(sum(increase(n1ql_requests_5000ms{cluster_name=`$cluster`}[$__range])))",
     "legendFormat": "5000ms"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(n1ql_requests{cluster_name=`$cluster`}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Query Execution time",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(n1ql_request_time{cluster_name=`$cluster`}[$__rate_interval]) / rate(n1ql_requests{cluster_name=`$cluster`}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}