{
 "title": "Single Cluster Information (6.x)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "multimanager_cluster_checker_status{cluster_name=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "cacheDurationSeconds": 30,
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*].host, function($h) {\n    $replace(\n      $replace($h, /:\\d+$/, \"\")\n    , /https?:\\/\\//, \"\")\n})",
       "language": "jsonata",
       "name": "Hostname"
      },
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")})",
       "language": "jsonata",
       "name": "Version"
      },
      { "jsonPath": "$.nodes_summary[*].os", "language": "jsonpath", "name": "Operating System" },
      {
       "jsonPath": "$map($.nodes_summary[*], function($node) {\n  $join($sort($map($node.services, function ($svc) {\n    $svc = \"cbas\" ? \"Analytics\" :\n    $svc = \"n1ql\" ? \"Query\" :\n    $svc = \"eventing\" ? \"Eventing\" :\n    $svc = \"index\" ? \"Index\" :\n    $svc = \"fts\" ? \"Search\" :\n    $svc = \"kv\" ? \"Data\" :\n    $svc = \"backup\" ? \"Backup\" : $svc\n  })), \", \")\n})",
       "language": "jsonata",
       "name": "Services"
      },
      { "jsonPath": "$.nodes_summary[*].cpuCount", "language": "jsonata", "name": "CPUs" },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  $formatNumber($round($node.mem_total / 1024 / 1024), \"#,###;(#0.00)\") & \" MB\"\n})",
       "language": "jsonata",
       "name": "Total RAM"
      },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  $round((1 - ($node.mem_free / $node.mem_total)) * 100, 2) & \"%\"\n})",
       "language": "jsonata",
       "name": "RAM Usage"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "cacheDurationSeconds": 30,
     "fields": [
      { "jsonPath": "$.buckets_summary[*].name", "name": "Name" },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $formatNumber($b.items, \"#,###\")\n})",
       "language": "jsonata",
       "name": "Items Stored"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $formatNumber($b.quota / 1024 / 1024, \"#,###\") & \" MB\"\n})",
       "language": "jsonata",
       "name": "Quota"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $round($b.quota_used, 2) & \"%\"\n})",
       "language": "jsonata",
       "name": "Quota Used",
       "type": "number"
      },
      {
       "jsonPath": "$.buckets_summary[*].num_replicas",
       "language": "jsonata",
       "name": "Replicas"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  { "title": "Health Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster Check Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    }
   ]
  },
  {
   "title": "Node Check Warnings",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} > 0"
    }
   ]
  },
  {
   "title": "Bucket Check Warnings",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} > 0"
    }
   ]
  },
  {
   "title": "Passing Health Checks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\ncount(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} == 0) + \ncount(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"} == 0) + \ncount(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"} == 0)\n) / (\ncount(multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"}) +\ncount(multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"}) +\ncount(multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"})\n)"
    }
   ]
  },
  {
   "title": "All Nodes Healthy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(\nmin(sum by (instance) (cbnode_healthy{cluster=${cluster:doublequote}})) / \nmax(sum by (instance) (cbnode_cluster_membership{cluster=${cluster:doublequote}}))\n)"
    }
   ]
  },
  {
   "title": "Healthy Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(count by (instance) (cbnode_healthy{cluster=${cluster:doublequote}} == 1))"
    }
   ]
  },
  { "title": "KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (cbpernodebucket_curr_connections{cluster=${cluster:doublequote}})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Total KV Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (cbpernodebucket_ops{cluster=${cluster:doublequote}})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GET Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (cbbucketstat_cmd_get{cluster=${cluster:doublequote}})",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "SET Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (cbbucketstat_cmd_set{cluster=${cluster:doublequote}})",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (bucket) (cbbucketstat_ep_cache_miss_rate{cluster=${cluster:doublequote}})",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Items Stored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (cbbucketstat_curr_items_tot{cluster=${cluster:doublequote}})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "cbquery_requests{cluster=${cluster:doublequote}}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cbquery_avg_req_time{cluster=${cluster:doublequote}}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index Memory Quota Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cbindex_memory_used{cluster=${cluster:doublequote}} / cbindex_memory_quota{cluster=${cluster:doublequote}}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slowest Scanning Indexes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, cbindex_avg_scan_latency{cluster=${cluster:doublequote}})",
     "legendFormat": "{{keyspace}} @ {{instance}}"
    }
   ]
  }
 ]
}