{
 "title": "Single Cluster Information (7.x)",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(multimanager_cluster_checker_status,cluster_name)"
    }
   },
   {
    "name": "cluster_uuid",
    "query": {
     "query": "multimanager_cluster_checker_status{cluster_name=\"$cluster\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview - at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$cluster", "language": "jsonata", "name": "Version", "type": "number" },
      { "jsonPath": "$now()", "language": "jsonata", "name": "Time", "type": "time" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")})",
       "language": "jsonata",
       "name": "Version",
       "type": "number"
      },
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$m := $now()})",
       "language": "jsonata",
       "name": "Time",
       "type": "time"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (node_uuid) (multimanager_node_checker_status{cluster_uuid=\"$cluster_uuid\"}))"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(group by (bucket) (multimanager_bucket_checker_status{cluster_uuid=\"$cluster_uuid\"}))"
    }
   ]
  },
  {
   "title": "Cluster Check Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"}"
    }
   ]
  },
  {
   "title": "Documents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kv_collection_item_count{cluster=\"$cluster\", collection=\"_default\"}",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 14 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*], function($node) {\n  $join($sort($map($node.services, function ($svc) {\n    $svc = \"cbas\" ? \"Analytics\" :\n    $svc = \"n1ql\" ? \"Query\" :\n    $svc = \"eventing\" ? \"Eventing\" :\n    $svc = \"index\" ? \"Index\" :\n    $svc = \"fts\" ? \"Search\" :\n    $svc = \"kv\" ? \"Data\" :\n    $svc = \"backup\" ? \"Backup\" : $svc\n  })), \", \")\n})",
       "language": "jsonata",
       "name": "Version",
       "type": "string"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    }
   ]
  },
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 22 },
   "targets": [
    {
     "fields": [
      {
       "jsonPath": "$map($.nodes_summary[*].host, function($h) {\n    $replace(\n      $replace($h, /:\\d+$/, \"\")\n    , /https?:\\/\\//, \"\")\n})",
       "language": "jsonata",
       "name": "hostname"
      },
      {
       "jsonPath": "$map($.nodes_summary[*].version, function($m) {$join($append($split($m, \"-\")[0], $replace($split($m, \"-\")[2], \"e\", \"E\", 1)), \" \")})",
       "language": "jsonata",
       "name": "Version"
      },
      { "jsonPath": "$.nodes_summary[*].os", "language": "jsonpath", "name": "Operating System" },
      {
       "jsonPath": "$map($.nodes_summary[*], function($node) {\n  $join($sort($map($node.services, function ($svc) {\n    $svc = \"cbas\" ? \"Analytics\" :\n    $svc = \"n1ql\" ? \"Query\" :\n    $svc = \"eventing\" ? \"Eventing\" :\n    $svc = \"index\" ? \"Index\" :\n    $svc = \"fts\" ? \"Search\" :\n    $svc = \"kv\" ? \"Data\" :\n    $svc = \"backup\" ? \"Backup\" : $svc\n  })), \", \")\n})",
       "language": "jsonata",
       "name": "Services"
      },
      { "jsonPath": "$.nodes_summary[*].cpuCount", "language": "jsonata", "name": "CPUs" },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  $formatNumber($round($node.mem_total / 1024 / 1024), \"#,###;(#0.00)\") & \" MiB\"\n})",
       "language": "jsonata",
       "name": "Total RAM"
      },
      {
       "jsonPath": "$map($.nodes_summary, function ($node) {\n  $round((1 - ($node.mem_free / $node.mem_total)) * 100, 2) & \"%\"\n})",
       "language": "jsonata",
       "name": "RAM Usage"
      },
      { "jsonPath": "$.nodes_summary[*].node_uuid", "language": "jsonpath", "name": "uuid" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    },
    {
     "expr": "max by (hostname) (label_replace(multimanager_node_checker_status{cluster_name=\"$cluster\"} > 0, \"hostname\", \"$1\", \"node_name\", \"(.+)(:[0-9]+)$\"))"
    }
   ]
  },
  {
   "title": "Cluster Health Issues",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 22 },
   "targets": [
    {
     "expr": "multimanager_cluster_checker_status{cluster_uuid=\"$cluster_uuid\"} > 0"
    }
   ]
  },
  {
   "title": "Dataset",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 30 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.buckets_summary[*].name", "name": "bucket" },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $formatNumber($b.items, \"#,###\")\n})",
       "language": "jsonata",
       "name": "Items Stored"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $formatNumber($b.quota / 1024 / 1024, \"#,###\") & \" MiB\"\n})",
       "language": "jsonata",
       "name": "Quota"
      },
      {
       "jsonPath": "$map($.buckets_summary[*], function($b) {\n  $round($b.quota_used, 2) & \"%\"\n})",
       "language": "jsonata",
       "name": "Quota Used",
       "type": "number"
      },
      {
       "jsonPath": "$.buckets_summary[*].num_replicas",
       "language": "jsonata",
       "name": "Replicas"
      }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid"
    },
    {
     "cacheDurationSeconds": 300,
     "expr": "count by (bucket) (index_items_count{cluster=`$cluster`}) or max by (bucket) (clamp_max(kv_ops, 0))",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "expr": "count by (bucket) (multimanager_bucket_checker_status{cluster_name=`$cluster`} > 0)"
    },
    {
     "expr": "min by (bucket) (kv_vb_perc_mem_resident_ratio{cluster=`$cluster`,state=\"active\"})"
    }
   ]
  },
  {
   "title": "Connected KV Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 30 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.connections[*].sdk_name", "name": "SDK/Client" },
      { "jsonPath": "$.connections[*].sdk_version", "language": "jsonpath", "name": "SDK Version" },
      {
       "jsonPath": "$.connections.user.($ = null ? \"\" : $replace($.name, /<\\/?ud>/, \"\"))",
       "language": "jsonata",
       "name": "Username"
      },
      { "jsonPath": "$.connections[*].source.ip", "language": "jsonpath", "name": "Source IP" },
      { "jsonPath": "$.connections[*].agent_name", "language": "jsonpath", "name": "" }
     ],
     "method": "GET",
     "urlPath": "/clusters/$cluster_uuid/connections"
    }
   ]
  },
  { "title": "KPIs - Data Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "GET Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ops{cluster=\"$cluster\",op=\"get\"}[$__rate_interval]))",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "SET Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(kv_ops{cluster=`$cluster`,op=~\"set.*\"}[$__rate_interval]))",
     "legendFormat": "{{ instance}}"
    }
   ]
  },
  {
   "title": "Reads 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"GET\"}[5m])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Writes 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,bucket) (rate(kv_cmd_duration_seconds_bucket{cluster=`$cluster`,opcode=\"SET\"}[5m])))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  { "title": "KPIs - Query Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(n1ql_requests{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(n1ql_request_time[$__rate_interval]) / increase(n1ql_requests[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "KPIs - Index Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Index Memory Quota Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "index_memory_used_total{cluster=${cluster:doublequote}} / index_memory_quota{cluster=${cluster:doublequote}}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slowest Scanning Indexes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, index_avg_scan_latency{cluster=${cluster:doublequote}})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Largest Indexes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(4, index_data_size{cluster=${cluster:doublequote}})",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}