{
 "title": "Configuration Check",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clusters",
    "query": {
     "query": "query_result(count by (cluster) (cbnode_up) or count by (cluster) (label_replace(count by (cluster_name) (multimanager_cluster_checker_status), \"cluster\", \"$1\", \"cluster_name\", \"(.*)\")))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Configuration Check\n\nIf all the checks below report OK, and the number of nodes and clusters is right, you're all set! Head over to the [Cluster Overview Dashboard](/d/g-waunKnz/cluster-overview-dashboard) to get started.\n\nIf any report a problem, or the number of nodes does not match your expectations, review the [setup instructions](https://docs.couchbase.com)."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Prometheus Scrape Targets",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "targets": [
    { "expr": "min by (job) (up)" }
   ]
  },
  {
   "title": "Configured Clusters",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (cbbucketinfo_up))",
     "legendFormat": "Prometheus Exporter"
    },
    {
     "expr": "count(count by (cluster_uuid) (multimanager_cluster_checker_status))",
     "legendFormat": "Couchbase Cluster Monitor"
    }
   ]
  },
  {
   "title": "Clusters Without Prometheus Exporter",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "count by (cluster) (label_replace(count by (cluster_name) (multimanager_cluster_checker_status), \"cluster\", \"$1\", \"cluster_name\", \"(.*)\"))\nunless\ncount by (cluster) (cbnode_up)"
    }
   ]
  },
  {
   "title": "Clusters Missing from Cluster Monitor",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "count by (cluster) (cbnode_up) unless count by (cluster) (label_replace(count by (cluster_name) (multimanager_cluster_checker_status), \"cluster\", \"$1\", \"cluster_name\", \"(.*)\"))"
    }
   ]
  },
  {
   "title": "All Clusters Registered + Exporter Configured?",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\ncount by (cluster) (label_replace(count by (cluster_name) (multimanager_cluster_checker_status), \"cluster\", \"$1\", \"cluster_name\", \"(.*)\"))\nand\ncount by (cluster) (cbnode_up)\n)"
    }
   ]
  },
  {
   "title": "Couchbase Prometheus Exporter ($clusters)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "clusters"
  },
  {
   "title": "Couchbase Exporter Checks",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "count(count by (node) (cbbucketinfo_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbbucketinfo"
    },
    {
     "expr": "count(count by (node) (cbbucketstat_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbnode"
    },
    {
     "expr": "count(count by (node) (cbcbas_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbcbas (Analytics)"
    },
    {
     "expr": "count(count by (node) (cbeventing_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbeventing (Eventing)"
    },
    {
     "expr": "count(count by (node) (cbfts_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbfts (Search)"
    },
    {
     "expr": "count(count by (node) (cbindex_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbindex (Index)"
    },
    {
     "expr": "count(count by (node) (cbnode_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbnode"
    },
    {
     "expr": "count(count by (node) (cbpernode_bucketstats_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbpernode_bucketstats (Data)"
    },
    {
     "expr": "count(count by (node) (cbquery_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbquery (Query)"
    },
    {
     "expr": "count(count by (node) (cbtask_up{cluster=${clusters:doublequote}}))",
     "legendFormat": "cbtask"
    }
   ]
  },
  {
   "title": "Configured Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cbbucketinfo_up{cluster=${clusters:doublequote}})",
     "legendFormat": "Prometheus Exporter"
    },
    {
     "expr": "count(count by (node_uuid) (multimanager_node_checker_status{cluster_name=${clusters:doublequote}}))",
     "legendFormat": "Couchbase Cluster Monitor"
    }
   ]
  },
  {
   "title": "Nodes Without Prometheus Exporter",
   "type": "table",
   "description": "If nodes appear in this panel despite both being added to the Cluster Monitor and Prometheus, check if alternate addresses are enabled. If so, ensure you are using the alternate address to refer to the node in your Prometheus service discovery configuration.",
   "gridPos": { "h": 12, "w": 3, "x": 9, "y": 15 },
   "targets": [
    {
     "expr": "count by (node) (label_replace(count by (node_name) (multimanager_node_checker_status{cluster_name=${clusters:doublequote}}), \"node\", \"$1\", \"node_name\", \"(.*)(?::[0-9]*$)\")) unless count by (instance) (cbnode_up)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 21 },
   "options": {
    "content": "**Note:** If the number of nodes for a particular service does not equal the total number of nodes in the cluster, this may be because that node is not configured to run the respective service. In this case, the discrepancy can be ignored."
   }
  }
 ]
}