run:
  build-tags: [noui, gen]
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  lll:
    line-length: 120
  nestif:
    min-complexity: 6
  goimports:
    local-prefixes: github.com/couchbaselabs/cbmultimanager
