---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.21.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1
      hooks:
          - id: yamlfmt
            args: [--mapping, '4', --sequence, '6', --offset, '4', --width, '100']

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: no-commit-to-branch
