exclude: microlith/html/tern-licensing-report.html

repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.2.1 # put latest release tag from https://github.com/ansible-community/ansible-lint/releases/
    hooks:
      - id: ansible-lint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: script
        entry: tools/shellcheck.sh
      - id: licence-lint
        name: licence-lint
        language: script
        entry: tools/licence-lint.sh

  - repo: https://github.com/golangci/golangci-lint
    rev: "v1.42.1"
    hooks:
      - id: golangci-lint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        # This will conflict with Grafana's exported files - avoid fighting and unnecessary diffs
        exclude: ^microlith/grafana/provisioning/dashboards/.*\.json$
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: no-commit-to-branch
