// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	memcached "github.com/couchbase/gomemcached/client"
	mock "github.com/stretchr/testify/mock"

	tls "crypto/tls"
)

// McClientFactory is an autogenerated mock type for the mcClientFactory type
type McClientFactory struct {
	mock.Mock
}

// CreateClient provides a mock function with given fields: host, username, password, config
func (_m *McClientFactory) CreateClient(host string, username string, password string, config *tls.Config) (*memcached.Client, error) {
	ret := _m.Called(host, username, password, config)

	var r0 *memcached.Client
	if rf, ok := ret.Get(0).(func(string, string, string, *tls.Config) *memcached.Client); ok {
		r0 = rf(host, username, password, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*memcached.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, *tls.Config) error); ok {
		r1 = rf(host, username, password, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMcClientFactory interface {
	mock.TestingT
	Cleanup(func())
}

// NewMcClientFactory creates a new instance of McClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMcClientFactory(t mockConstructorTestingTNewMcClientFactory) *McClientFactory {
	mock := &McClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
