---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: microlith-test-role
subjects:
- kind: ServiceAccount
  name: microlith-test-role
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin # Probably doesn't need this.
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microlith-test-role
---
apiVersion: v1
kind: Pod
metadata:
  name: microlith-test
spec:
  serviceAccountName: microlith-test-role
  restartPolicy: Never
  containers:
  - name: tester
    env:
    - name: TEST_NATIVE
      value: "false"
    - name: COUCHBASE_SERVER_IMAGE
      value: %%COUCHBASE_SERVER_IMAGE%%
    image: %%IMAGE%%
---