# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'observability-poc'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - alerting/*.yaml

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'loki'
    scrape_interval: 30s
    static_configs:
         - targets: ['localhost:3100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
#     static_configs:
#          - targets: ['cadvisor:8080']
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
         - targets: ['nodeexporter:9100']
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']
  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  # - job_name: 'node-problem-detector'
  #   static_configs:
  #     - targets: ['node_problem_detector:20257']
      
  - job_name: 'couchbase'
    scrape_interval: 5s
    static_configs:
         - targets: ['exporter_db1:9091', 'exporter_db2:9091', 'exporter_db3:9091' ]
  
  - job_name: 'fluentbit'
    static_configs:
         - targets: ['logging:2020']
  
  - job_name: 'blackbox'
    metrics_path: /probe 
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['db1:8091']
      # - targets: ['http://db1:8091/pools/default']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115 # Blackbox exporter.