groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'
      impact: "Something is failing"
      action: "To remediate fix the broken thing"
      dashboard: "https://grafana.com/service-dashboard"
      # What do do when this alert triggers - a URL for more information/remediation
      runbook: "https://wiki.com/whattodo"
      # Link to the logs...
      logurl: "https://grafana.com/log-explorer"
