---
groups:
  - name: Couchbase-Server
    rules:

    - alert: CB90038-statsCollectionFailed
      expr: |
        up{job=~`couchbase-server.*`} == 0
      for: 30s
      labels:
        job: couchbase_prometheus
        kind: node
        health_check_id: CB90038
        health_check_name: statsCollectionFailed
        cluster: '{{ $labels.cluster }}'
        node: '{{ $labels.instance }}'
        severity: critical
      annotations:
        title: Could not collect stats from {{ $labels.instance }} (cluster {{ $labels.cluster }})
        description: Statistics collection failed from node {{ $labels.instance }}. Either it is down or its CPU is overloaded.
        remediation: Verify the node's status and examine other metrics and health check results.

    - alert: CB90041-cpuStolenRate
      expr: |
        sys_cpu_stolen_rate > 3
      for: 30s
      labels:
        job: couchbase_prometheus
        kind: node
        health_check_id: CB90041
        health_check_name: cpuStolenRate
        cluster: '{{ $labels.cluster }}'
        node: '{{ $labels.instance }}'
        severity: warning
      annotations:
        title: High CPU steal rate on {{ $labels.instance }} (cluster {{ $labels.cluster }})
        description: The percentage of time that the virtual CPU on node {{ $labels.instance }} is waiting for a real CPU is above 3%.
          This can be due to the fact that a virtual Machine is undersized or the hypervisor is overcommited.
        remediation: Increase the resources available to the VM or reduce the number of VMs on the host machine.

    - alert: CB90043-diskCommitFail
      expr: |
        increase(kv_ep_data_write_failed[1m]) > 0
      for: 0m
      labels:
        job: couchbase_prometheus
        kind: bucket
        health_check_id: CB90043
        health_check_name: diskCommitFail
        cluster: '{{ $labels.cluster }}'
        node: '{{ $labels.instance }}'
        bucket: '{{ $labels.bucket }}'
        severity: critical
      annotations:
        title: "Disk Commit Fail on bucket: {{ $labels.bucket }}"
        description: A disk commit has failed on {{ $labels.bucket }} (cluster {{ $labels.cluster }}, node {{ $labels.instance }}).
        remediation: Review your infrastructure for signs of disk problems or any other issues, or contact Couchbase Technical Support.

    - alert: CB90055-metadataOverhead-Warning
      expr: |
        (kv_total_memory_overhead_bytes / kv_ep_max_size) > 0.5 < 0.9
      for: 0m
      labels:
        job: couchbase_prometheus
        kind: bucket
        health_check_id: CB90055
        health_check_name: metadataOverhead
        cluster: '{{ $labels.cluster }}'
        node: '{{ $labels.instance }}'
        bucket: '{{ $labels.bucket }}'
        severity: warning
      annotations:
        title: "Metadata Overhead Above 50% on Bucket: {{ $labels.bucket }}, Node: {{ $labels.instance }}"
        description: The percentage of memory that is taken up by metadata is over 50%
        remediation: Increase memory allocation for bucket or change the evictionPolicy of the bucket from `Value-only` (be aware this will have an adverse effect on performance).

    - alert: CB90055-metadataOverhead-Alert
      expr: |
        (kv_total_memory_overhead_bytes / kv_ep_max_size) >= 0.9
      for: 0m
      labels:
        job: couchbase_prometheus
        kind: bucket
        health_check_id: CB90055
        health_check_name: metadataOverhead
        cluster: '{{ $labels.cluster }}'
        node: '{{ $labels.instance }}'
        bucket: '{{ $labels.bucket }}'
        severity: critical
      annotations:
        title: "Metadata Overhead Above 90% on Bucket: {{ $labels.bucket }}, Node: {{ $labels.instance }}"
        description: The percentage of memory that is taken up by metadata is over 90%
        remediation: Increase memory allocation for bucket or change the evictionPolicy of the bucket from `Value-only` (be aware this will have an adverse effect on performance).
