{
 "title": "Couchbase-Single",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "bucket", "label": "bucket", "query": "label_values(bucket)" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cpu_utilization_rate{bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_mem_used_bytes{bucket=\"$bucket\"}"
    },
    {
     "expr": "cbbucketstat_mem_actual_used_bytes{bucket=\"$bucket\"}"
    },
    {
     "expr": "cbbucketstat_mem_actual_free{bucket=\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "cbpernodebucket_curr_connections{bucket=\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Ops Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_ops{bucket=\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Gets Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cmd_get{bucket=\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Sets Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_cmd_set{bucket=\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Items",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cbbucketstat_curr_items{bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Items Total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "cbbucketstat_curr_items_tot{bucket=~\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Disk Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_disk_write_queue{bucket=\"$bucket\"}"
    },
    {
     "expr": "cbbucketstat_ep_diskqueue_items{bucket=\"$bucket\"}"
    }
   ]
  },
  {
   "title": "Total Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_couch_total_disk_size{bucket=\"$bucket\"}"
    }
   ]
  },
  {
   "title": "vBucket Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cbbucketstat_vbuckets_active_queue_size{bucket=\"$bucket\"}"
    },
    {
     "expr": "cbbucketstat_vbuckets_pending_queue_size{bucket=\"$bucket\"}"
    },
    {
     "expr": "cbpernodebucket_vb_replica_queue_size{bucket=\"$bucket\"}"
    }
   ]
  }
 ]
}