= Cluster Monitor

If running with the Couchbase Cluster Monitor enabled, it will output the status of its checkers to Prometheus like the following:

----
# HELP multimanager_cluster_checker_status Checker results for cluster level checkers
# TYPE multimanager_cluster_checker_status gauge
multimanager_cluster_checker_status{cluster="961b7464aca17a7db150fb0e44be5849",name="singleOrTwoNodeCluster"} 1
# HELP multimanager_node_checker_status Checker results for node level checkers
# TYPE multimanager_node_checker_status gauge
multimanager_node_checker_status{cluster="961b7464aca17a7db150fb0e44be5849",name="nonGABuild",node="47a45d39583947823ac9866dce2a74b2"} 0
multimanager_node_checker_status{cluster="961b7464aca17a7db150fb0e44be5849",name="oneServicePerNode",node="47a45d39583947823ac9866dce2a74b2"} 1
multimanager_node_checker_status{cluster="961b7464aca17a7db150fb0e44be5849",name="supportedVersion",node="47a45d39583947823ac9866dce2a74b2"} 0
----

The values of each metric represent the current status of the checker. The integer values have the following meanings:

* 0: Good (everything is fine, no action required)
* 1: Warn (potential issue, worth investigating)
* 2: Alert (serious issue, action required)
* 3: Info (informational only, no action required)
* 4: Missing (checker failed to run or information was not available)

== Next steps

* xref:architecture.adoc[Architecture overview]
* xref:deployment-microlith.adoc[Microlith container deployment]
* xref:deployment-onpremise.adoc[On-premise deployment]
* xref:tutorial-onpremise.adoc[On-premise example]
