= Couchbase Monitoring and Observability Stack

The intention of this repository is to provide a simple, out-of-the-box solution based on industry standard tooling to observe the state of your Couchbase cluster.

* An additional requirement is to ensure we can integrate into existing observability pipelines people may already have as easily as possible.
* This must all support being deployed on-premise and on cloud platforms with minimal change.
* Any bespoke software must be minimal and ideally just restricted to configuration of generic tools.
* We must support customer configuration of what is "important" to monitor in their clusters although with best practice defaults provided.
* A simple and often upgrade pipeline to support frequent changes and updates to the solution which are then easy to roll out for users.

We essentially need to support two fairly distinct types of user:

. Those who have nothing and just want a simple working solution to monitor their cluster.
. Those who have an existing monitoring pipeline and want to integrate Couchbase monitoring into it, likely with a set of custom rules and configuration.

== Caveats and restrictions

* No support for data persistence is currently other than mounting the relevant volumes into the container.
* Limited compatibility by supporting migrating from previous version to latest version. Best efforts will be made but the intention is this iterates often and no backwards compatibility is provided. We will show how to migrate from X-1 to X but no more than that, users should be following an agile lifecycle of constant upgrade.
* The Couchbase cluster monitor is proprietary and requires access to the repository to build it into the container. The container can be built without it by removing it and there is a https://github.com/couchbaselabs/observability/tree/main/tools/build-oss-container.sh[helper script^] that does this.

== Feedback and support

Please use our official link:https://issues.couchbase.com/projects/CMOS/issues[JIRA board^] to report any bugs and issues with the appropriate components. We also encourage you to use the link:https://forums.couchbase.com[Couchbase Forums^] for posting any questions or feedback that you might have.

No official support is currently provided but best efforts will be made and we are keen to hear of any issues.

== Next steps

* xref:architecture.adoc[Architecture]
* xref:deployment-microlith.adoc[Microlith container deployment]
* xref:deployment-onpremise.adoc[On-premise deployment]
