= Integrating CMOS with an existing monitoring pipeline
:icons: font
:imagesdir: ../assets/images
ifdef::env-github[]
:imagesdir: https://github.com/couchbaselabs/observability/raw/main/docs/modules/ROOT/assets/images
endif::[]

[abstract]
You can integrate CMOS with your existing Prometheus, Alertmanager, and Grafana monitoring system. 
This tutorial documents how to configure each component in order to achieve this.

include::partial$tutorial.adoc[]

== Overview
In this tutorial we will detail the steps needed to configure existing Prometheus, Alertmanager, and Grafana instances to integrate with Couchbase Monitoring and Observability Stack (CMOS).

Depending on which parts of the stack you are already running, you may need to consult our xref:tutorial-standalone.adoc[Standalone Installation tutorial], which has sections on how to install each component.

Each section within these tutorials designed to be independent, so only follow the configuration steps required.

== Prometheus

Once you have completed all of the below steps you may need to restart Prometheus to apply the configuration changes.

=== Configuring the Scrape config for your Couchbase cluster

You will need to modify your existing Prometheus configuration file (typically named `prometheus.yml`).

See our xref:tutorial-standalone.adoc#_install_prometheus[Install Prometheus] documentation for an example of what this file should look like with an appropriate Couchbase Server / Cluster Monitor `scrape_config`.

=== Install Prometheus Alerting Rules

Follow the Standalone tutorial instructions on xref:tutorial-standalone.adoc#_prometheus_alerting_rules[Installing Prometheus Alerting rules].

== Alertmanager

=== Downloading and installing Alert templates

Follow the instructions in the xref:tutorial-standalone.adoc#_prometheus_alerting_rules[Standalone example guide].

== Cluster Monitor

See xref:tutorial-standalone.adoc#_install_cluster_monitor[Install Cluster Monitor] on how to run the Cluster Monitor.

== Grafana

=== Install all required Grafana plugins

The linked instructions for each plugin offer a Grafana Cloud one-click install, a command-line based install for a running instance, or a `.zip` file which can be unpacked manually into your Grafana plugins directory. 
If you prefer to use configuration files, or run Grafana in a Docker container, you may prefer an alternative install method (see below).

. https://grafana.com/grafana/plugins/marcusolsson-json-datasource/[JSON API], which has associated https://grafana.com/grafana/plugins/marcusolsson-json-datasource/?tab=installation[installation instructions].

==== Alternative install methods
If you:

- Configure Grafana (v7.1+) dashboards through the use of provisioning files: https://grafana.com/docs/grafana/latest/administration/provisioning/#plugins[specify the plugins to install in your provisioning configuration file]. 
- Are running Grafana in a Docker container: simply pass through an additional environment variable `GF_INSTALL_PLUGINS=$PLUGIN_NAME $VERSION` where the `$PLUGIN_NAME` and latest `$VERSION` can be found on the plugin's homepage (linked under "installation instructions" for each). 

=== Download and install CMOS dashboards

The dashboards can be found in the official GitHub repository under https://github.com/couchbaselabs/observability/tree/main/microlith/grafana/provisioning/dashboards[microlith/grafana/provisioning/dashboards]/.

Download them and copy them to a folder accessible by your Grafana installation. 

The relevant setting in the Grafana configuration file, typically named `grafana.ini`, is:

[source, console]
----
[dashboards.json]
enabled = true
path = <desired path>/dashboards
----

If you are using https://grafana.com/docs/grafana/latest/administration/provisioning/[Grafana provisioning], you will need to update the `providers.options.path` argument in your provisioning configuration file (typically named `grafana.yml`).
For example:

[source, console]
----
providers:
  ...
  options:
    ...
    # <string, required> path to dashboard files on disk. Required when using the 'file' type
    path: /etc/grafana/provisioning/dashboards/
    ...
  ...
...
----

=== Configure Grafana Data Sources

Now we have the required plugins and dashboards installed, we need to configure the required Data Sources:

. **Prometheus** - if you're running Grafana, you likely already have a Prometheus instance configured as a Data Source. 
If not, the Standalone tutorial has instructions on xref:tutorial-standalone.adoc#_configuring_grafana_data_sources[adding a Prometheus Data Source].
. **Cluster Monitor (JSON API)** - click on _Add Data Source_ and select "JSON API". The URL should point to the Cluster Monitor, which listens on port `:7196`, with a sub-path of `/api/v1`. 
Enable `basicAuth`, with the user and password you configured.
. **Alertmanager** - this should follow the same steps as JSON API, except the URL will be `protocol://FQDN:9093/alertmanager/api/v2`, and `basicAuth` may not be required. 

If you are utilizing Grafana provisioning for dashboards, then your `grafana.yml` may look something like this:
[source, console]  
----
...
   - name: JSON API
      type: marcusolsson-json-datasource
      url: http://localhost:7196/api/v1
      basicAuth: true
      basicAuthUser: ${CB_MULTI_ADMIN_USER}
      basicAuthPassword: ${CB_MULTI_ADMIN_PASSWORD}
    - name: Alertmanager API
      type: marcusolsson-json-datasource
      url: http://localhost:9093/alertmanager/api/v2
...
---- 

If this is not the case (i.e., you only configure a `grafana.ini` file), you will need to add these Data Sources using the web UI. 
Follow the xref:tutorial-standalone.adoc#_configuring_grafana_data_sources[Configuring Grafana Data Sources] instructions for a general guide on how to do this.

== Next Steps

You should now have a complete CMOS stack up and running. 
You may wish to build upon and change the existing Grafana dashboards and Prometheus / Alertmanager alerts for your use-case.