// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	values "github.com/couchbaselabs/cbmultimanager/values"
)

// MonitorIFace is an autogenerated mock type for the MonitorIFace type
type MonitorIFace struct {
	mock.Mock
}

// HeartBeatCluster provides a mock function with given fields: cluster
func (_m *MonitorIFace) HeartBeatCluster(cluster *values.CouchbaseCluster) error {
	ret := _m.Called(cluster)

	var r0 error
	if rf, ok := ret.Get(0).(func(*values.CouchbaseCluster) error); ok {
		r0 = rf(cluster)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: heartBeatFrequency
func (_m *MonitorIFace) Start(heartBeatFrequency time.Duration) {
	_m.Called(heartBeatFrequency)
}

// Stop provides a mock function with given fields:
func (_m *MonitorIFace) Stop() {
	_m.Called()
}
