# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'observability-poc'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - alerting/*.yaml

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

# https://github.com/prometheus/prometheus/blob/main/config/testdata/conf.good.yml
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'loki'
    scrape_interval: 30s
    static_configs:
         - targets: ['localhost:3100']
  - job_name: 'pushgateway'
    scrape_interval: 30s
    honor_labels: true
    static_configs:
      - targets: ['localhost:9091']
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9100']
  - job_name: 'couchbase'
    scrape_interval: 10s
    file_sd_configs:
      - files:
        - 'couchbase/targets.json'
        refresh_interval: 30s
  - job_name: 'couchbase-cluster'
    basic_auth:
      username: admin
      password: password
    scrape_interval: 10s
    metrics_path: /api/v1/_prometheus
    static_configs:
      - targets: ['localhost:7196']