---
groups:
    - name: Base
      rules:
          - alert: TestUntouched
            expr: untouched
          - alert: TestExprOverride
            expr: overridden{}
          - alert: TestDisabled
            expr: disabled{}
