---
modules:
  default:
    headers:
      X-Dummy: my-test-header
    metrics:


  terse_cluster_info:
    metrics:
    - name: terse_cluster_info
      type: object
      help: /pools/default/terseClusterInfo
      path: '{  }'
      labels:
        clusterUUID: '{ .clusterUUID }'
        orchestrator: '{ .orchestrator }'
      values:

        clusterCompatVersion: '{ .clusterCompatVersion }'

  autofailover:
    metrics:
    - name: autofailover
      type: object
      help: /settings/autoFailover
      path: '{  }'

      values:
        enabled: '{ .enabled }'
        timeout: '{ .timeout }'
        count: '{ .count }'
  pools:
    metrics:
    - name: xdcr_tasks
      type: object
      help: Couchbase XDCR tasks info
      path: '{}'
      values:
        id: '{ .id }'
        source_bucket: '{ .source }'
        target_path: '{ .target }'
        status: '{ .status }'
        replication_type: '{ .replicationType }'
        continuous: '{ .continuous }'
        docs_checked: '{ .docsChecked }'
        docs_written: '{ .docsWritten }'
        changes_left: '{ .changesLeft }'
        refresh_period: '{ .recommendedRefreshPeriod }'
      filters:
        - .type == "xdcr"

