// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	values "github.com/couchbaselabs/cbmultimanager/cluster-monitor/pkg/values"
)

// MonitorIFace is an autogenerated mock type for the MonitorIFace type
type MonitorIFace struct {
	mock.Mock
}

// HeartBeatCluster provides a mock function with given fields: cluster
func (_m *MonitorIFace) HeartBeatCluster(cluster *values.CouchbaseCluster) error {
	ret := _m.Called(cluster)

	var r0 error
	if rf, ok := ret.Get(0).(func(*values.CouchbaseCluster) error); ok {
		r0 = rf(cluster)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: heartBeatFrequency
func (_m *MonitorIFace) Start(heartBeatFrequency time.Duration) {
	_m.Called(heartBeatFrequency)
}

// Stop provides a mock function with given fields:
func (_m *MonitorIFace) Stop() {
	_m.Called()
}

type mockConstructorTestingTNewMonitorIFace interface {
	mock.TestingT
	Cleanup(func())
}

// NewMonitorIFace creates a new instance of MonitorIFace. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMonitorIFace(t mockConstructorTestingTNewMonitorIFace) *MonitorIFace {
	mock := &MonitorIFace{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
