services:

    # A basic example compose file
    cmos:

        container_name: cmos
        image: couchbase-observability-stack:v1
        build:
            # Build using build kit so we can do ssh mounts for private repo, do not build here.
            # Unfortunately Docker Compose does not use locally built images, it tries to pull them  unless you specify 'build'
            context: ../../../microlith/

        ports:
            - "8080:8080"

        # Add to custom network so CMOS and server/exporter containers can communicate and resolve container names to IPs
        networks:
            - shared_network

networks:
    shared_network:
