---
# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
# deleteDatasources:
  # - name: Loki
  # - name: Prometheus

# list of datasources to insert/update depending
# whats available in the database
datasources:
# https://grafana.com/docs/grafana/latest/datasources/loki/#configure-the-data-source-with-provisioning
    - name: Loki
      type: loki
      access: proxy
      url: http://localhost:3100${CMOS_HTTP_PATH_PREFIX}
      jsonData:
          maxLines: 1000
    - name: Prometheus
      type: prometheus
      uid: PBFA97CFB590B2093
      access: proxy
      url: http://localhost:9090${CMOS_HTTP_PATH_PREFIX}/prometheus
      basicAuth: false
      isDefault: true
  # <map> fields that will be converted to json and stored in json_data
      jsonData:
          graphiteVersion: '1.1'
          tlsAuth: false
          tlsAuthWithCACert: false
  # <string> json object of data that will be encrypted.
      secureJsonData:
          tlsCACert: '...'
          tlsClientCert: '...'
          tlsClientKey: '...'
      version: 1
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://localhost:16686/
    - name: JSON API
      type: marcusolsson-json-datasource
      uid: PD5070BC1AA9F8304
      url: http://localhost:7196/api/v1
      basicAuth: true
      basicAuthUser: ${CB_MULTI_ADMIN_USER}
      basicAuthPassword: ${CB_MULTI_ADMIN_PASSWORD}
    - name: Alertmanager API
      type: marcusolsson-json-datasource
      uid: PC245499EF542F9C5
      url: http://localhost:9093${CMOS_HTTP_PATH_PREFIX}/alertmanager/api/v2
