{
 "title": "Couchbase Backup Service",
 "tags": [
  "Couchbase",
  "Couchbase-7",
  "Backup-Service",
  "Backup"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(backup_data_size,cluster_name)"
    }
   },
   {
    "name": "repository",
    "label": "Repository",
    "query": {
     "query": "label_values(backup_data_size{cluster_name=~\"$cluster\"},repository)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(backup_data_size{cluster_name=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Data Size",
   "type": "timeseries",
   "description": "Repository backed up data size",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "backup_data_size{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\"}",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Dispatched Tasks to be Run",
   "type": "timeseries",
   "description": "Number of tasks dispatched dispatched to be run",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(backup_dispatched{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Location Checks Performed",
   "type": "timeseries",
   "description": "Number of location checks performed",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(backup_location_check{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{repository}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (BACKUP) - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg by(le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"BACKUP\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (BACKUP) - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"BACKUP\"}))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"BACKUP\"}))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"BACKUP\"}))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"BACKUP\"}))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"BACKUP\"}))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (BACKUP) - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg by (repository, le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"BACKUP\"}))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (INFO) - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"INFO\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (INFO) - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"INFO\"}))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"INFO\"}))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"INFO\"}))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"INFO\"}))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"INFO\"}))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (INFO) - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg by (repository, le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"INFO\"}))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (MERGE) - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"MERGE\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (MERGE) - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"MERGE\"}))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"MERGE\"}))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"MERGE\"}))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"MERGE\"}))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"MERGE\"}))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (MERGE) - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg by (repository, le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"MERGE\"}))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (RESTORE) - Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"RESTORE\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (RESTORE) - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"RESTORE\"}))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"RESTORE\"}))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"RESTORE\"}))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"RESTORE\"}))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, avg by (le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"RESTORE\"}))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "Backup Tasks Times (RESTORE) - 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg by (repository, le) (backup_task_duration_seconds_bucket{cluster_name=~\"$cluster\",repository=~\"$repository\",instance=~\"$node\",task_type=\"RESTORE\"}))",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sysproc_cpu_utilization{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_size{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_resident{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_share{cluster_name=\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "description": "CPU Utilization per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n avg(\n    rate(\n      node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n  * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "backup and memcached CPU Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n    rate(\n      namedprocess_namegroup_cpu_seconds_total{instance=~\"$node\",groupname=~\"(memcached|backup|cbbackupmgr).*\",mode=~\"user|system\"}[$__rate_interval]\n    ) \n) by (instance, groupname)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "description": "Memory Utilization  per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\n  1 \n  - \n  (\n    avg(\n      avg_over_time(\n        node_memory_MemFree_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Cached_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Buffers_bytes{instance=~\"$node\"}[$__rate_interval]\n      )\n    ) by (instance)\n  )\n  / \n  avg(node_memory_MemTotal_bytes{instance=~\"$node\"}\n  ) by (instance)\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "backup and memcached Memory Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"(memcached|backup|cbbackupmgr).*\",memtype=\"swapped\"}[$__rate_interval])\n  + \n  ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"(memcached|backup|cbbackupmgr).*\",memtype=\"resident\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Write bytes - {{instance}}"
      },
      {
       "expr": "-sum(rate(node_disk_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Read bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "backup and memcached Disk Operations",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "-sum(rate(namedprocess_namegroup_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(memcached|backup|cbbackupmgr).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - read - {{instance}}"
      },
      {
       "expr": "sum(rate(namedprocess_namegroup_write_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(memcached|backup|cbbackupmgr).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - write - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - TX"
      },
      {
       "expr": "-sum(rate(node_network_receive_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - RX"
      }
     ]
    },
    {
     "title": "backup and memcached Open File Descriptors",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\n  max_over_time(namedprocess_namegroup_open_filedesc{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(memcached|backup|cbbackupmgr).*\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}