{
 "title": "Couchbase Eventing Service",
 "tags": [
  "Couchbase",
  "Couchbase-7",
  "Eventing-Service",
  "Eventing",
  "OnUpdate",
  "OnDelete",
  "Timer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(eventing_on_update_success,cluster_name)"
    }
   },
   {
    "name": "func_name",
    "label": "Function",
    "query": {
     "query": "label_values(eventing_on_update_success{cluster_name=~\"$cluster\"},functionName)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(eventing_on_update_success{cluster_name=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Remaining Mutations",
   "type": "timeseries",
   "description": "Remaining mutations to process",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (functionName) (eventing_dcp_backlog{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "OnUpdate Success Rate/sec",
   "type": "timeseries",
   "description": "Total OnUpdate handler executions that have succeeded for all functions",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(functionName) (rate(eventing_on_update_success{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "OnDelete Success Rate/sec",
   "type": "timeseries",
   "description": "Total OnDelete handler executions that have succeeded for all functions",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(functionName) (rate(eventing_on_delete_success{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "OnDelete Failure Rate/sec",
   "type": "timeseries",
   "description": "The total number OnDelete handler executions that have failed for all functions",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(functionName) (rate(eventing_on_delete_failure{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "OnUpdate Failure Rate/sec",
   "type": "timeseries",
   "description": "Total OnUpdate handler executions that have failed for all functions\n",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(functionName) (rate(eventing_on_update_failure{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "Queue Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(functionName) (eventing_agg_queue_memory{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(functionName) (eventing_agg_queue_size{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "Worker Spawns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(functionName) (eventing_worker_spawn_counter{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "{{functionName}}"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sysproc_cpu_utilization{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_size{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_resident{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_share{cluster_name=\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "description": "CPU Utilization per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n avg(\n    rate(\n      node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n  * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eventing CPU Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n    rate(\n      namedprocess_namegroup_cpu_seconds_total{instance=~\"$node\",groupname=~\"eventing.*\",mode=~\"user|system\"}[$__rate_interval]\n    ) \n) by (instance, groupname)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "description": "Memory Utilization  per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\n  1 \n  - \n  (\n    avg(\n      avg_over_time(\n        node_memory_MemFree_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Cached_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Buffers_bytes{instance=~\"$node\"}[$__rate_interval]\n      )\n    ) by (instance)\n  )\n  / \n  avg(node_memory_MemTotal_bytes{instance=~\"$node\"}\n  ) by (instance)\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "eventing Memory Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"eventing.*\",memtype=\"swapped\"}[$__rate_interval])\n  + \n  ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"eventing.*\",memtype=\"resident\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Write bytes - {{instance}}"
      },
      {
       "expr": "-sum(rate(node_disk_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Read bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "eventing Disk Operations",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "-sum(rate(namedprocess_namegroup_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"eventing.*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - read - {{instance}}"
      },
      {
       "expr": "sum(rate(namedprocess_namegroup_write_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"eventing.*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - write - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - TX"
      },
      {
       "expr": "-sum(rate(node_network_receive_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - RX"
      }
     ]
    },
    {
     "title": "eventing Open File Descriptors",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\n  max_over_time(namedprocess_namegroup_open_filedesc{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"eventing.*\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timer Callback Success Rate/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_timer_callback_success{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timer Cancel Rate/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_timer_cancel_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timer Create Rate/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_timer_create_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timer Callback Failure Rate/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_timer_callback_failure{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timer Context Size Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (increase(eventing_timer_context_size_exception_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timer Create Failure Rate/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_timer_create_failure{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timer Messages/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_timer_msg_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timer Callback Missing",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (increase(eventing_timer_callback_missing_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bucket Op Exceptions",
     "type": "timeseries",
     "description": "otal number of bucket operations inside of an Eventing function which have resulted in an exception",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (increase(eventing_bucket_op_exception_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Bucket Op (CAS Mismatch) Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (increase(eventing_bkt_ops_cas_mismatch_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "N1QL Exceptions",
     "type": "timeseries",
     "description": "Total number of N1QL operations inside of an Eventing function which have resulted in an exception",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (increase(eventing_n1ql_op_exception_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Timeouts",
     "type": "timeseries",
     "description": "Total number of handler executions were terminated because the handler ran longer than the configured script timeout",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (increase(eventing_timeout_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "Checkpoint Failures",
     "type": "timeseries",
     "description": "Total number of failures when checkpointing last processed sequence numbers by v8 worker. Failures are retried using exponential backoff until timeout.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (increase(eventing_checkpoint_failure_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "DCP Mutations Sent to Worker/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_dcp_mutation_sent_to_worker{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "DCP Mutations Messags/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_dcp_mutations_msg_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "DCP Deletes Sent to Worker/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_dcp_deletion_sent_to_worker{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "DCP Delete Messages/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_dcp_delete_msg_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "DCP Expiry Sent to Worker/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_dcp_expiry_sent_to_worker{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "DCP Mutations Suppressed/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_dcp_mutation_suppressed_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    },
    {
     "title": "DCP Deletes Suppressed/sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by(functionName) (rate(eventing_dcp_deletion_suppressed_counter{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{functionName}}"
      }
     ]
    }
   ]
  }
 ]
}