{
 "title": "Couchbase Index Service",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "index",
  "gsi",
  "moi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(index_memory_quota,cluster_name)"
    }
   },
   {
    "name": "bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(index_num_requests{cluster_name=~\"$cluster\"},bucket)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(index_memory_quota{cluster_name=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Index Count by Bucket",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "{{bucket}}"
    }
   ]
  },
  {
   "title": "Index Count by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index Memory by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(index_memory_used{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index Items by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(index_items_count{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index Requests by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg. Scan Time by Node",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(index_avg_scan_latency{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}>0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Index Distribution by Bucket",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "Indexes"
    },
    {
     "expr": "sum(index_memory_used{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum(index_items_count{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "Item Count"
    },
    {
     "expr": "avg(index_avg_scan_latency{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}>0) by (bucket)",
     "legendFormat": "Avg. Scan Latency"
    },
    {
     "expr": "avg(index_resident_percent{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"} > 0) by (bucket)",
     "legendFormat": "Avg. Resident Ratio"
    },
    {
     "expr": "avg(rate(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}[$__rate_interval])>0) by (bucket)",
     "legendFormat": "Avg. Scans / Sec"
    },
    {
     "expr": "avg(index_avg_item_size{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}>0) by (bucket)",
     "legendFormat": "Avg. Item Size"
    },
    {
     "expr": "count(index_avg_item_size{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\",index=~\".*primary*\"}>0) by (bucket)",
     "legendFormat": "Primary Indexes"
    },
    {
     "expr": "sum(index_data_size_on_disk{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (bucket)",
     "legendFormat": "Size On Disk"
    }
   ]
  },
  {
   "title": "Index Distribution by Node",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (instance)",
     "legendFormat": "Indexes"
    },
    {
     "expr": "sum(index_memory_used{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (instance)",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "sum(index_items_count{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (instance)",
     "legendFormat": "Item Count"
    },
    {
     "expr": "avg(index_avg_scan_latency{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}>0) by (instance)",
     "legendFormat": "Avg. Scan Latency"
    },
    {
     "expr": "avg(index_resident_percent{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"} > 0) by (instance)",
     "legendFormat": "Avg. Resident Ratio"
    },
    {
     "expr": "avg(rate(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}[$__rate_interval])>0) by (instance)",
     "legendFormat": "Avg. Scans / Sec"
    },
    {
     "expr": "avg(index_avg_item_size{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}>0) by (instance)",
     "legendFormat": "Avg. Item Size"
    },
    {
     "expr": "count(index_avg_item_size{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\",index=~\".*primary*\"}>0) by (instance)",
     "legendFormat": "Primary Indexes"
    },
    {
     "expr": "sum(index_data_size_on_disk{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (instance)",
     "legendFormat": "Size On Disk"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sysproc_cpu_utilization{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_size{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_resident{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_share{cluster_name=\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n avg(\n    rate(\n      node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n  * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "indexer and projector CPU Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n    rate(\n      namedprocess_namegroup_cpu_seconds_total{instance=~\"$node\",groupname=~\"(indexer|projector).*\",mode=~\"user|system\"}[$__rate_interval]\n    ) \n) by (instance, groupname)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\n  1 \n  - \n  (\n    avg(\n      avg_over_time(\n        node_memory_MemFree_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Cached_bytes{instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Buffers_bytes{instance=~\"$node\"}[$__rate_interval]\n      )\n    ) by (instance)\n  )\n  / \n  avg(node_memory_MemTotal_bytes{instance=~\"$node\"}\n  ) by (instance)\n) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "indexer and projector Memory Usage",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"(indexer|projector).*\",memtype=\"swapped\"}[$__rate_interval])\n  + \n  ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{instance=~\"$node\",groupname=~\"(indexer|projector).*\",memtype=\"resident\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Write bytes - {{instance}}"
      },
      {
       "expr": "-sum(rate(node_disk_read_bytes_total{instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Read bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "indexer and projector Disk Operations",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(namedprocess_namegroup_write_bytes_total{instance=~\"$node\",groupname=~\"(indexer|projector).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - write - {{instance}}"
      },
      {
       "expr": "-sum(rate(namedprocess_namegroup_read_bytes_total{instance=~\"$node\",groupname=~\"(indexer|projector).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - read - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "-sum(rate(node_network_receive_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - RX"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - TX"
      }
     ]
    },
    {
     "title": "indexer and projector Open File Descriptors",
     "type": "timeseries",
     "description": "Requires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\n  max_over_time(namedprocess_namegroup_open_filedesc{instance=~\"$node\",groupname=~\"(indexer|projector).*\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Largest Indexes by Size",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "topk(10, index_data_size{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"})"
      }
     ]
    },
    {
     "title": "Top 10 Slowest Scanning Indexes by Size",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "topk(10, index_avg_scan_latency{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"})"
      }
     ]
    },
    {
     "title": "Top 10 Largest Indexes by Items",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "topk(10, index_items_count{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"})"
      }
     ]
    },
    {
     "title": "Indexes with Zero Items",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "index_items_count{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}==0"
      }
     ]
    },
    {
     "title": "Indexes Never Scanned",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}==0"
      }
     ]
    },
    {
     "title": "Indexes without Replicas",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "count without(instance) (label_replace(index_num_requests{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}, \"index\", \"$1\", \"index\", \"([^ ]+).*\")) == 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "items_count",
     "type": "timeseries",
     "description": "The number of items in the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(index_items_count{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "avg_item_size",
     "type": "timeseries",
     "description": "The average index entry size\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(index_avg_item_size{cluster_name=~\"$cluster\",instance=~\"$node\",bucket=~\"$bucket\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "cache_hits",
     "type": "timeseries",
     "description": "The number of in-memory hits to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(index_cache_hits{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "cache_misses",
     "type": "timeseries",
     "description": "The number of in-memory misses to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(index_cache_misses{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "memory_used",
     "type": "timeseries",
     "description": "The amount of memory used by the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(index_memory_used{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "avg_scan_latency",
     "type": "timeseries",
     "description": "The average latency when scanning the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "avg(index_avg_scan_latency{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "index_resident_percent",
     "type": "timeseries",
     "description": "The percentage of the index that is memory resident.  Indexes w/ 0 items are omitted\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(index_resident_percent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}> 0) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "cache_misses",
     "type": "timeseries",
     "description": "The ratio of misses to hits\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(index_cache_misses{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "num_docs_indexed",
     "type": "timeseries",
     "description": "The number of items indexed since the last restart\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(index_num_docs_indexed{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "num_docs_pending",
     "type": "timeseries",
     "description": "The number of documents that are pending\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(index_num_docs_pending{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "num_docs_queued",
     "type": "timeseries",
     "description": "The number of documents that are queued for indexing\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(index_num_docs_queued{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "disk_size",
     "type": "timeseries",
     "description": "The size of the index on disk\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(index_disk_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "num_requests",
     "type": "timeseries",
     "description": "The number of requests to the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(index_num_requests{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "data_size",
     "type": "timeseries",
     "description": "The total data size of the index\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(index_data_size{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "recs_in_mem",
     "type": "timeseries",
     "description": "The number of records in the index that are in memory\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(index_recs_in_mem{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "index_frag_percent",
     "type": "timeseries",
     "description": "The index fragmentation percentage\n",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(index_frag_percent{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "num_rows_returned",
     "type": "timeseries",
     "description": "The average number of rows returned by a scan\n",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(index_num_rows_returned{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "scan_bytes_read",
     "type": "timeseries",
     "description": "The average number of bytes read per scan\n",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(index_scan_bytes_read{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "recs_on_disk",
     "type": "timeseries",
     "description": "The number of records not in memory\n",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(index_recs_on_disk{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    },
    {
     "title": "total_scan_duration",
     "type": "timeseries",
     "description": "The total time spent scanning",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "avg(rate(index_total_scan_duration{cluster_name=~\"$cluster\",bucket=~\"$bucket\",instance=~\"$node\"}[$__rate_interval])) by (bucket)",
       "legendFormat": "{{bucket}}"
      }
     ]
    }
   ]
  }
 ]
}