{
 "title": "Couchbase Query Service",
 "tags": [
  "couchbase",
  "couchbase-7",
  "couchbase-service",
  "couchbase-query",
  "n1ql"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(n1ql_requests,cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Query Nodes",
    "query": {
     "query": "label_values(n1ql_requests{cluster_name=~\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "N1QL Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(n1ql_load{cluster_name=~\"$cluster\",instance=~\"$node\"})",
     "legendFormat": "Results"
    }
   ]
  },
  {
   "title": "Avg. N1QL Result Count",
   "type": "stat",
   "description": "Results Per Second",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(n1ql_result_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Results"
    }
   ]
  },
  {
   "title": "Average Response Size",
   "type": "stat",
   "description": "Average bytes of the response size",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(n1ql_result_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Response Size"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "stat",
   "description": "Average Execution Time (Overall), Average Service Time (time spent executing)",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(n1ql_request_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Average Service Time",
   "type": "stat",
   "description": "Average Service Time (time spent executing)",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(n1ql_service_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Average Queue Time",
   "type": "stat",
   "description": "The time spent waiting to be executed",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(n1ql_request_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) - (rate(n1ql_service_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Queries/sec Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg by (le) (\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"5000\", \"\", \"\"))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries in Range Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "avg by (le) (\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"5000\", \"\", \"\")\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries All-time Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "avg by (le) (\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"5000\", \"\", \"\")\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries/sec - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (le) (\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"+Inf\", \"\", \"\")))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (le) (\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"+Inf\", \"\", \"\")))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (le) (\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"+Inf\", \"\", \"\")))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (le) (\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"+Inf\", \"\", \"\")))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, avg by (le) (\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n    -\n    rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])\n  , \"le\", \"+Inf\", \"\", \"\")))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "Queries in Range - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (le) (\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (le) (\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (le) (\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (le) (\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, avg by (le) (\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n    -\n    increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "Queries All-Time - Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, avg by (le) (\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, avg by (le) (\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, avg by (le) (\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, avg by (le) (\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.999, avg by (le) (\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"250\", \"\", \"\")\n  or \n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"500\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"1000\", \"\", \"\")\n  or\n  label_replace(\n    n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}\n    -\n    n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  , \"le\", \"+Inf\", \"\", \"\")\n))",
     "legendFormat": "99.9th Percentile"
    }
   ]
  },
  {
   "title": "N1QL Queries",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "> 250ms"
    },
    {
     "expr": "sum(rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "> 500ms"
    },
    {
     "expr": "sum(rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "> 1000ms"
    },
    {
     "expr": "sum(rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "> 5000ms"
    },
    {
     "expr": "sum(rate(n1ql_queued_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "queued"
    },
    {
     "expr": "sum(rate(n1ql_prepared{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "prepared"
    }
   ]
  },
  {
   "title": "N1QL Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(n1ql_at_plus{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "at_plus"
    },
    {
     "expr": "sum(rate(n1ql_cancelled{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "cancelled"
    },
    {
     "expr": "sum(rate(n1ql_invalid_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "invalid"
    },
    {
     "expr": "sum(rate(n1ql_scan_plus{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "scan_plus"
    },
    {
     "expr": "sum(rate(n1ql_unbounded{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "unbounded"
    },
    {
     "expr": "sum(rate(n1ql_transactions{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "transactions"
    }
   ]
  },
  {
   "title": "N1QL errors/warnings",
   "type": "timeseries",
   "description": "The number o N1QL errors, warnings, invalid requests and queued requests",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(n1ql_errors{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(increase(n1ql_warnings{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Warnings"
    },
    {
     "expr": "sum(increase(n1ql_invalid_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  {
   "title": "N1QL Operations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(n1ql_updates{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "UPDATEs"
    },
    {
     "expr": "sum(rate(n1ql_selects{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "SELECTs"
    },
    {
     "expr": "sum(rate(n1ql_inserts{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "INSERTs"
    },
    {
     "expr": "sum(rate(n1ql_deletes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "DELETEs"
    },
    {
     "expr": "sum(rate(n1ql_transactions{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "N1QL Index Scans",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(n1ql_index_scans{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "Index Scans"
    },
    {
     "expr": "sum(rate(n1ql_primary_scans{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "Primary Scans"
    }
   ]
  },
  {
   "title": "Average Execution Time",
   "type": "timeseries",
   "description": "Average Execution Time (Overall), Average Service Time (time spent executing)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(rate(n1ql_request_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "Request Time"
    },
    {
     "expr": "-avg(rate(n1ql_service_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "Service Time"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Processes",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sysproc_cpu_utilization{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_size{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_resident{cluster_name=\"$cluster\",instance=~\"$node\"}"
      },
      {
       "expr": "sysproc_mem_share{cluster_name=\"$cluster\",instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "CPU Utilization ",
     "type": "timeseries",
     "description": "CPU Utilization per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (\n avg(\n    rate(\n      node_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\",mode=\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n  * 100\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cbq-engine CPU Usage",
     "type": "timeseries",
     "description": "CPU Utilization for cbq-engine process per Node.\n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n    rate(\n      namedprocess_namegroup_cpu_seconds_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(cbq-engine).*\",mode=~\"user|system\"}[$__rate_interval]\n    ) \n) by (instance, groupname)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "description": "Memory Utilization  per Node.\n\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * (\n  1 \n  - \n  (\n    avg(\n      avg_over_time(\n        node_memory_MemFree_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Cached_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]\n      ) + \n      avg_over_time(\n        node_memory_Buffers_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]\n      )\n    ) by (instance)\n  )\n  / \n  avg(node_memory_MemTotal_bytes{cluster_name=~\"$cluster\",instance=~\"$node\"}\n  ) by (instance)\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "cbq-engine Memory Usage",
     "type": "timeseries",
     "description": "Memory Usage for cbq-engine process per Node.\n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(\n  avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(cbq-engine).*\",memtype=\"swapped\"}[$__rate_interval])\n  + \n  ignoring (memtype) avg_over_time(namedprocess_namegroup_memory_bytes{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(cbq-engine).*\",memtype=\"resident\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "-sum(rate(node_disk_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Read bytes - {{instance}}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) by (instance)",
       "legendFormat": "Write bytes - {{instance}}"
      }
     ]
    },
    {
     "title": "cbq-engine Disk Operations",
     "type": "timeseries",
     "description": "Disk Operations for cbq-engine process per Node. \n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "-sum(rate(namedprocess_namegroup_read_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(cbq-engine).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - read - {{instance}}"
      },
      {
       "expr": "sum(rate(namedprocess_namegroup_write_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(cbq-engine).*\"}[$__rate_interval])) by (groupname, instance)",
       "legendFormat": "{{groupname}} - write - {{instance}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface.\nRequires Node Exporter Metrics (https://github.com/prometheus/node_exporter)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "-sum(rate(node_network_receive_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - RX"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])*8) by (instance)",
       "legendFormat": "{{instance}} - TX"
      }
     ]
    },
    {
     "title": "cbq-engine Open File Descriptors",
     "type": "timeseries",
     "description": "The # of Open File Descriptors for the cbq-engine process. \n\nRequires Process Exporter (https://github.com/ncabatoff/process-exporter)\n",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(\n  max_over_time(namedprocess_namegroup_open_filedesc{cluster_name=~\"$cluster\",instance=~\"$node\",groupname=~\"(cbq-engine).*\"}[$__rate_interval])\n) by (groupname, instance)",
       "legendFormat": "{{groupname}} - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Queries",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range]))",
       "legendFormat": "queries"
      }
     ]
    },
    {
     "title": "Query Requests by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Errors by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(n1ql_errors{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Avg. Request Time by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "n1ql_avg_req_time{cluster_name=~\"$cluster\",instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Avg. Service Time by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "n1ql_avg_svc_time{cluster_name=~\"$cluster\",instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Avg. Result Size by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "n1ql_avg_response_size{cluster_name=~\"$cluster\",instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Timings",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range]))\n-\nsum(increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range]))",
       "legendFormat": "0-250ms"
      },
      {
       "expr": "sum(increase(\n  n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range]\n))",
       "legendFormat": "250-499ms"
      },
      {
       "expr": "sum(\n  increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n)",
       "legendFormat": "500-999ms"
      },
      {
       "expr": "sum(\n  increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n)",
       "legendFormat": "1000-4999ms"
      },
      {
       "expr": "sum(\n  increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n)",
       "legendFormat": ">5000ms"
      }
     ]
    },
    {
     "title": "Query Requests (0-249ms) by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(\n  increase(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n) by (instance)\n-\nsum(\n  increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])\n) by (instance)"
      }
     ]
    },
    {
     "title": "Query Requests (>250ms) by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Requests (>500ms) by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Requests (>1000ms) by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Requests (>5000ms) by Node",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__range])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "N1QL Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL at_plus Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_at_plus{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Cancelled Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_cancelled{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Queued N1QL Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(n1ql_queued_requests{cluster_name=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL scan_plus Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_scan_plus{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Unbounded Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_unbounded{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Invalid Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_invalid_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Index Scans",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_index_scans{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Primary Index Scans",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_primary_scans{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "N1QL Queries (<250ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Queries (>250ms < 500ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_requests_250ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Queries (> 500ms < 1000ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_requests_500ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Queries (>1000ms < 5000ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_requests_1000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Queries (>5000ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_requests_5000ms{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Service Time",
     "type": "timeseries",
     "description": "Average Service Time (time spent executing)",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(n1ql_service_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Request Time",
     "type": "timeseries",
     "description": "Average Execution Time (Overall), Average Service Time (time spent executing)",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "rate(n1ql_request_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Queue Time",
     "type": "timeseries",
     "description": "The time spent waiting to be executed",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "(rate(n1ql_request_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])) - (rate(n1ql_service_time{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "N1QL SELECT Operations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_selects{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL UPDATE Operations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_updates{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL INSERT Operations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_inserts{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "INSERTs"
      }
     ]
    },
    {
     "title": "N1QL DELETE Operations",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_deletes{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Transactions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_transactions{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Load",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "n1ql_load{cluster_name=~\"$cluster\",instance=~\"$node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Prepared ",
     "type": "timeseries",
     "description": "Prepared Executions per second",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(n1ql_prepared{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "N1QL Result Count",
     "type": "timeseries",
     "description": "Results Per Second",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(n1ql_result_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Average Response Size",
     "type": "timeseries",
     "description": "Average bytes of the response size",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(n1ql_result_count{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]) / rate(n1ql_requests{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Warnings",
     "type": "timeseries",
     "description": "The number of N1QL warnings",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(n1ql_warnings{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Errors",
     "type": "timeseries",
     "description": "The number o N1QL errors",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(n1ql_errors{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Auditing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "N1QL Audit Actions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(n1ql_audit_actions{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Audit Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(n1ql_audit_requests_total{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Filtered Audit Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(n1ql_audit_requests_filtered{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "N1QL Failed Audit Actions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(n1ql_audit_actions_failed{cluster_name=~\"$cluster\",instance=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}