pipeline {
  agent {
    label 'docker'
  }

  stages {
    stage('Build & test distribution') {
      steps {
        sh 'make clean test-dist-oss'
      }
    }
  }

  post {
    always {
      sh 'make clean'
      cleanWs()
    }
  }
}
