# This is a simple compose stack to represent an example of an on-premise deployment.
# We run the couchbase server "stuff" as a set of containers but this is just a simulation and equivalent to running natively.
# We then run the microlith container to monitor the couchbase cluster.

version: "3"

# Split into front-end and back-end networks although front-end is probably unnecessary
networks:
    front:
    back:

services:

    # This first section is the main thrust of the microlith, it runs the all-in-one container up
    couchbase-grafana:
        # Build using build kit so we can do ssh mounts for private repo, do not build here
        # build: .
        image: couchbase-observability:latest
        container_name: couchbase-grafana
        volumes:
            # Mount various node exporter paths for metrics - may be superceded by Couchbase Server
            # You can also disable node exporter usage by setting the relevant env var
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/host/rootfs:ro
            # This location stores any dynamic Prometheus info (e.g. targets to scrape)
            # Update as necessary and it should be automatically picked up at the next interval (5m)
            - ./dynamic/prometheus/couchbase/:/etc/prometheus/couchbase/:rw
        networks:
            - front
            - back
        ports:
            # Grafana
            - "3000:3000"
            # Prometheus
            - "9090:9090"
            # Healthcheck
            - "7196-7197:7196-7197"
            # Fluent bit forwarding
            - "24224:24224"

    # This section is intended to represent a typical local deployment, instead of containers it could be done with native binaries
    db1:
        container_name: db1
        # image: couchbase:6.6.2
        image: couchbase/server-sandbox:6.6.0
        ports:
            - "8091-8096:8091-8096"
            - "11210-11211:11210-11211"
        volumes:
            - log-volume:/opt/couchbase/var/lib/couchbase/logs/:rw
        networks:
            - back

    permission-fixer:
        image: bash
        # CB server forces this on us as the permissions for the rebalance directory as well as logs are not for all
        # https://issues.couchbase.com/browse/MB-46485
        command: sh -c "mkdir -p /opt/couchbase/var/lib/couchbase/logs/rebalance; while true; do sleep 10;chmod -R a+r /opt/couchbase/var/lib/couchbase/logs/; done"
        user: root
        volumes:
            - log-volume:/opt/couchbase/var/lib/couchbase/logs/:rw

    logging:
        container_name: logging
        image: couchbase/fluent-bit:1.0.3
        ports:
            # Metrics
            - "2020:2020"
        depends_on:
            - db1
        environment:
            - COUCHBASE_LOGS=/opt/couchbase/var/lib/couchbase/logs
        volumes:
            - log-volume:/opt/couchbase/var/lib/couchbase/logs/:ro
            - ./fluent-bit.conf.server:/fluent-bit/config/fluent-bit.conf:ro
        networks:
            - back

    exporter:
        container_name: exporter
        image: couchbase/exporter:1.0.4
        command:
            - '--couchbase-address=db1'
        ports:
            - "9091:9091"
        depends_on:
            - db1
        networks:
            - back

volumes:
    log-volume:
