services:

    # A basic example compose file
    cmos:

        container_name: cmos
        image: couchbase-observability:v1
        build:
            # Build using build kit so we can do ssh mounts for private repo, do not build here.
            # Unfortunately Docker Compose does not use locally built images, it tries to pull them  unless you specify 'build'
            context: ../../microlith/

        # Use bridge network otherwise the CMOS container would be on a different network to the CB Server and exporter containers,
        # and would not be able to communicate with them (docker-compose defaults to a different network to docker CLI)
        network_mode: bridge
        ports:
            - "8080:8080"
