services:

    cmos:

        container_name: cmos
        image: couchbase-observability:v1
        build:
            # Build using build kit so we can do ssh mounts for private repo, do not build here.
            # Unfortunately Docker Compose does not use locally built images, it tries to pull them unless you specify 'build'
            context: ../../microlith/

        # Change to bridge network as by default docker-compose is on a different network
        network_mode: bridge
        ports:
            - "8080:8080"
