services:

    cmos:

        container_name: cmos
        image: couchbase-observability:v1
        build:
            # Build using build kit so we can do ssh mounts for private repo, do not build here.
            # Unfortunately Docker Compose does not use locally built images, it tries to pull them unless you specify 'build'
            context: ../../microlith/

        environment:
            - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
        
        volumes:
            - ./dynamic/grafana:/etc/grafana:rw
        
        ports:
            - "8080:8080"
