---
openapi: 3.0.3
info:
    title: Couchbase Monitoring & Observability Stack - Configuration Service
    description: REST API of the Configuration Service
    version: v1
    contact:
        name: Couchbase, Inc.
        url: https://couchbase.com
        email: info@couchbase.com
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
servers:
    - description: Local Microlith
      url: http://localhost:8080/config/api/v1
    - description: Local Development
      url: http://localhost:7194/api/v1
paths:
    /openapi.json:
        get:
            summary: Outputs the OpenAPI specification for this API.
            responses:
                '200':
                    description: OpenAPI 3.0 specification for this API
                    content:
                        application/json:
                            schema:
                                type: object
    /clusters/add:
        post:
            summary: Add a new Couchbase cluster to Prometheus
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Cluster'
            responses:
                '200':
                    description: Cluster added successfully
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties: false
                                required: [ok]
                                properties:
                                    ok:
                                        type: boolean
                                        enum: [true]
    /alertsConfiguration:
        get:
            summary: Get the current alert notification configuration
            responses:
                '200':
                    description: Current Alertmanager notification configuration
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AlertNotificationConfig"
        put:
            summary: Update the alert notification configuration
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AlertNotificationConfig"
            responses:
                '200':
                    description: Alert notification config successfully updated
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AlertNotificationConfig"
                '400':
                    description: Invalid input
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
    /collectInformation:
        post:   # avoid accidental activation by GET
            summary: Collects diagnostic information about CMOS for Support analysis.
            responses:
                '200':
                    description: Stream of logging output from collect-information.sh
                    content:
                        text/plain: {}
components:
    schemas:
        Cluster:
            type: object
            additionalProperties: false
            required: [couchbaseConfig, hostname]
            properties:
                name:
                    type: string
                couchbaseConfig:
                    type: object
                    additionalProperties: false
                    required: [username, password]
                    properties:
                        managementPort:
                            type: number
                            default: 8091
                        username:
                            type: string
                        password:
                            type: string
                        useTLS:
                            type: boolean
                metricsConfig:
                    type: object
                    additionalProperties: false
                    properties:
                        metricsPort:
                            type: number
                hostname:
                    type: string
        ErrorResponse:
            type: object
            additionalProperties: false
            required: [ok, error]
            properties:
                ok:
                    type: boolean
                    enum: [false]
                error:
                    type: string
        AlertNotificationConfig:
            type: object
            additionalProperties: false
            properties:
                slack:
                    $ref: "#/components/schemas/SlackAlertNotificationConfig"
                email:
                    $ref: "#/components/schemas/EmailAlertNotificationConfig"
        SlackAlertNotificationConfig:
            type: object
            additionalProperties: false
            required: [webhookURL]
            properties:
                configuredExternally:
                    type: boolean
                    description: The Slack webhook has been configured using slack_api_file, and cannot be managed by CMOS.
                webhookURL:
                    type: string
                    format: url
        EmailAlertNotificationConfig:
            type: object
            additionalProperties: false
            required: [from, host]
            properties:
                from:
                    type: string
                host:
                    type: string
                hello:
                    type: string
                username:
                    type: string
                password:
                    type: string
                identity:
                    type: string
                secret:
                    type: string
                requireTLS:
                    type: boolean