server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: promtail-cmos
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: cmos
      __path__: /var/log/*log
  - targets:
      - localhost
    labels:
      job: logs
      host: cmos
      __path__: /logs/*log
