# Main workflow
name: main CICD build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.adoc'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build container and standard CICD pipeline
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test clone
        run: apt update && apt install -y openssh-client git && git clone --depth 1 git@github.com:couchbaselabs/cbmultimanager.git

      - name: Run makefile
        run: |
          DOCKER_USER=docker.io/couchbaselabs DOCKER_TAG=${{ github.sha }} make all

