# Main workflow
name: main CICD build

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run standard build
        run: |
          DOCKER_USER=docker.io/couchbase DOCKER_TAG=${{ github.sha }} make all

