# Main workflow
name: main CICD build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.adoc'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build OSS container
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run standard CICD pipeline but only for OSS
        run: |
          IMAGE_TAG=docker.io/couchbase/observability-stack:${{ github.sha }} make clean build lint container-lint container-oss dist test-dist

