# Main workflow
name: main CICD build

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.adoc'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build container and standard CICD pipeline
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run makefile
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          DOCKER_USER=docker.io/couchbaselabs DOCKER_TAG=${{ github.sha }} make all

