# Main workflow
name: Build and test changes

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.adoc'
  pull_request:
    branches:
      - main

jobs:
  cancel-identical-runs:
    name: Cancel any other runs
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      # Prevent duplication on PRs and branch pushes
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  # TODO: split into push testing (smaller, just smoke) and PR testing (all of matrix)
  build-test-oss-containers-and-k8s:
    name: CICD for the OSS variant (Containers and K8s)
    needs: cancel-identical-runs
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        server-version: [ '6.6.3' ] #, '7.0.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install BATS
        timeout-minutes: 5
        run: |
          sudo npm install -g bats

      - name: Create K8S Kind Cluster
        timeout-minutes: 10
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: kind-${{ github.sha }}

      # TODO: cache single container build across matrix runs
      - name: Run ${{ matrix.server-version }} tests
        run: |
          make container-oss test-containers test-kubernetes -e COUCHBASE_SERVER_IMAGE=couchbase/server:${{ matrix.server-version }} -e DOCKER_USER=docker.io/couchbaselabs -e DOCKER_TAG=${{ github.sha }}
  
  build-test-oss-native:
    name: CICD for the OSS variant (Native)
    needs: cancel-identical-runs
    runs-on: macos-10.15
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        server-version: [ '6.6.3' ] #, '7.0.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Install requirements
        timeout-minutes: 5
        run: |
          brew install ansible
          sudo npm install -g bats

      - name: Run ${{ matrix.server-version }} tests
        run: |
          make container-oss test-native -e COUCHBASE_SERVER_IMAGE=couchbase/server:${{ matrix.server-version }} -e DOCKER_USER=docker.io/couchbaselabs -e DOCKER_TAG=${{ github.sha }}

  linting:
    name: Run static analysis and linting tools
    needs: cancel-identical-runs
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linting
        run: |
          make lint

