# Main workflow
name: Build and test changes

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.adoc'
  pull_request:
    branches:
      - main

jobs:
  build-test-oss:
    name: CICD for the OSS variant
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        makefile-target: [ 'test-native', 'test-kubernetes' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install BATS
        timeout-minutes: 5
        run: |
          sudo npm install -g bats

      - name: Create K8S Kind Cluster
        if: ${{ matrix.makefile-target }} == 'test-kubernetes'
        timeout-minutes: 10
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: kind-${{ github.sha }}

      - name: Run ${{ matrix.makefile-target }} tests
        run: |
          make container-oss ${{ matrix.makefile-target }} -e DOCKER_USER=docker.io/couchbaselabs -e DOCKER_TAG=${{ github.sha }}

  linting:
    name: Run static analysis and linting tools
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linting
        run: |
          make lint

