---
name: PR - Loki rule tests
# Validate our Loki alerting rules

on:
    pull_request:
        branches:
            - main
        paths:
            - microlith/loki/alerting/**
            - testing/loki_alerts/**

jobs:
    unit-tests:
        name: Unit test Loki rules
        runs-on: ubuntu-20.04
        timeout-minutes: 15
        steps:
            - run: |
                echo "ref: ${{ github.event.inputs.ref }}"
                echo "user: ${{ github.event.inputs.user }}"

            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Run tests
              run: make test-loki-rules
