# Main workflow
name: Build and test changes ready for PR signoff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-oss-containers:
    name: Smoke tests - OSS - containers
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        server-version: [ '6.6.3' ] #, '7.0.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install BATS
        timeout-minutes: 5
        run: |
          sudo npm install -g bats

      # TODO: cache single container build across matrix runs
      - name: Run ${{ matrix.server-version }} tests
        run: |
          make TEST_SUITE=smoke container-oss test-containers -e COUCHBASE_SERVER_IMAGE=couchbase/server:${{ matrix.server-version }} -e DOCKER_USER=docker.io/couchbaselabs -e DOCKER_TAG=${{ github.sha }}

  # TODO: once CMOS-97 is done, add something similar for k8s

  linting:
    name: Run static analysis and linting tools
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linting
        run: |
          sudo apt install aspell
          make lint

