# Main workflow
name: Build and test changes ready for PR signoff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # TODO: split into push testing (smaller, just smoke) and PR testing (all of matrix)
  build-test-oss:
    name: CICD for the OSS variant
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        server-version: [ '6.6.3' ] #, '7.0.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install BATS
        timeout-minutes: 5
        run: |
          sudo npm install -g bats

      - name: Create K8S Kind Cluster
        timeout-minutes: 10
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: kind-${{ github.sha }}

      # TODO: cache single container build across matrix runs
      - name: Run ${{ matrix.server-version }} tests
        run: |
          make container-oss test-native test-containers test-kubernetes -e COUCHBASE_SERVER_IMAGE=couchbase/server:${{ matrix.server-version }} -e DOCKER_USER=docker.io/couchbaselabs -e DOCKER_TAG=${{ github.sha }}

  linting:
    name: Run static analysis and linting tools
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linting
        run: |
          sudo apt install aspell
          make lint

