---
name: PR - Build and test changes

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
  # Ensure we always run unit tests
    run-unit-tests:
        name: Run PR unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run makefile target for unit tests
              run: |
                  make test-unit

  # Build an image to share across jobs
    build-amd-oss-container:
        name: Build amd OSS container for testing
        runs-on: ubuntu-20.04
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build OSS container and export
              run: |
                  make image-artifacts -e VERSION=0.0.0 -e BLD_NUM=999 -e BINARY_TARGET=linux-arm64 IMAGE_BINARY_TARGET=linux-arm64 OSS=true
                  TAG=${{ github.sha }} tools/build-container-from-archive.sh dist/couchbase-observability-stack-image_0.0.0-999.tgz amd64
                  docker save --output /tmp/cmos-image.tar couchbase/observability-stack:${{ github.sha }}

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: cmos-image
                  path: /tmp/cmos-image.tar

    smoke-test-amd-oss-containers:
        name: Smoke tests - amd OSS - containers
        needs: build-amd-oss-container
        runs-on: ubuntu-20.04
        timeout-minutes: 60
        strategy:
            fail-fast: false
            matrix:
                server-version: [6.6.3, 7.0.2]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: cmos-image
                  path: /tmp

            - name: Load CMOS image
              run: |
                  docker load --input /tmp/cmos-image.tar
                  docker image ls -a

            - name: Install BATS
              timeout-minutes: 5
              run: |
                  sudo npm install -g bats

            - name: Run ${{ matrix.server-version }} tests
              run: |
                  make TEST_SUITE=smoke test-containers -e COUCHBASE_SERVER_VERSION=${{ matrix.server-version }} -e DOCKER_USER=couchbase -e DOCKER_TAG=${{ github.sha }}

            - name: Capture cmosinfo if something went wrong
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: test-failure-cmosinfo-${{ matrix.server-version }}
                  path: testing/diagnostics/cmosinfo/*

    build-arm-oss-container:
        name: Build arm OSS container for testing
        runs-on: ubuntu-20.04
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build OSS container and export
              run: |
                  make image-artifacts -e VERSION=0.0.0 -e BLD_NUM=999 -e BINARY_TARGET=linux-arm64 IMAGE_BINARY_TARGET=linux-arm64 OSS=true
                  TAG=${{ github.sha }} tools/build-container-from-archive.sh dist/couchbase-observability-stack-image_0.0.0-999.tgz arm64
                  docker save --output /tmp/cmos-image.tar couchbase/observability-stack:${{ github.sha }}

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: cmos-image
                  path: /tmp/cmos-image.tar

    smoke-test-arm-oss-containers:
        name: Smoke tests - arm OSS - containers
        needs: build-arm-oss-container
        runs-on: ubuntu-20.04
        timeout-minutes: 60
        strategy:
            fail-fast: false
            matrix:
                server-version: [6.6.3, 7.0.2]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: cmos-image
                  path: /tmp

            - name: Load CMOS image
              run: |
                  docker load --input /tmp/cmos-image.tar
                  docker image ls -a

            - name: Install BATS
              timeout-minutes: 5
              run: |
                  sudo npm install -g bats

            - name: Run ${{ matrix.server-version }} tests
              run: |
                  make TEST_SUITE=smoke test-containers -e COUCHBASE_SERVER_VERSION=${{ matrix.server-version }} -e DOCKER_USER=couchbase -e DOCKER_TAG=${{ github.sha }}

            - name: Capture cmosinfo if something went wrong
              if: ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: test-failure-cmosinfo-${{ matrix.server-version }}
                  path: testing/diagnostics/cmosinfo/*
  # TODO: once CMOS-97 is done, add something similar for k8s

    linting:
        name: Run static analysis and linting tools
        runs-on: ubuntu-20.04
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run linting
              run: |
                  sudo apt install aspell
                  pip3 install "ansible-lint[community,yamllint]"
                  make lint
