---
name: Publish to GitHub Pages
on:
    push:
        branches: [main]
        paths:
            - docs/**
    workflow_dispatch:
        inputs:
            ref:
                description: Branch, tag, or commit SHA to run against
                required: false
                default: main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.ref || 'main' }}

            - name: Run Antora
              uses: kameshsampath/antora-site-action@v0.2.4
              with:
                  antora_playbook: docs/antora-gh-playbook.yml

            - name: Publish to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: build/site
