name: tern-license-analysis
on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            ref:
                description: Branch, tag, or commit SHA to run against
                required: false
                default: main
jobs:
    tern-scan:
        name: Carry out analysis of the container image licensing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.inputs.ref || 'main' }}

            - name: Build an image from Dockerfile
              run: |
                make image-artifacts -e VERSION=0.0.0 -e BLD_NUM=999 -e OSS=true
                TAG=${{ github.sha }} tools/build-container-from-archive.sh dist/couchbase-observability-stack-image_0.0.0-999.tgz

            - uses: philips-labs/tern-action@v1.3.0
              id: scan
              with:
                image: couchbase/observability-stack:${{ github.sha }}
                format: human
                output: cmos-tern.out

            - uses: actions/upload-artifact@v2
              with:
                name: tern
                path: ${{ steps.scan.outputs.file }}
