name: tern-license-analysis
on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            ref:
                description: Branch, tag, or commit SHA to run against
                required: false
                default: main
jobs:
    tern-scan:
        name: Carry out analysis of the container image licensing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.ref || 'main' }}

            - name: Build an image from Dockerfile
              run: |
                  make container-oss -e CMOS_IMAGE=couchbaselabs/observability-stack:${{ github.sha }}

            - uses: philips-labs/tern-action@v1.2.0
              id: scan
              with:
                image: couchbaselabs/observability-stack:${{ github.sha }}
                format: human
                output: cmos-tern.out

            - uses: actions/upload-artifact@v2
              with:
                name: tern
                path: ${{ steps.scan.outputs.file }}
