cluster:
  logging:
    server:
      enabled: true
      manageConfiguration: false # Provide custom configuration to use
      configurationName: fluent-bit-custom # Name of the secret to use
      sidecar:
        image: couchbase/fluent-bit:1.0.4
  monitoring:
    prometheus:
      enabled: true
  servers:
    default:
      volumeMounts:
        default: couchbase
  volumeClaimTemplates:
  - metadata:
      name: couchbase
    spec:
      resources:
        requests:
          storage: 1Gi